version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "docs-site/**"
  - package-ecosystem: "npm"
    directory: "/docs-site"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
