/**
 * Generated by doc-generator 0.1.0. DO NOT EDIT.
 */

/**
 * ColorLike
 */
type ColorLike = Color | { r: number; g: number; b: number; a?: number };
/**
 * Task: cancellable promise.
 */
type Task<Result> = Promise<Result> & {
    cancel(): void;
};

/**
 * ProgressTask: task with progress.
 */
type ProgressTask<Result, Progress> = Task<Result> & {
    [Symbol.asyncIterator](): AsyncIterator<Progress>;
};
/**
 * NameLike
 */
type NameLike = string | Wildcard | RegExp;
/**
 * PointLike
 */
type PointLike = Point | { x: number; y: number };
/**
 * RectLike
 */
type RectLike = Rect | { x: number; y: number; width: number; height: number };
/**
 * SizeLike
 */
type SizeLike = Size | { width: number; height: number };
/**
 * Pauses the execution.
 */
declare function sleep(ms: number): Task<void>;
/**
 * Stops the execution.
 */
declare function exit(): void;
declare function formatFrequency(frequency: number): string;
declare function formatPercent(percent: number, precision?: number): string;
declare function formatBytes(bytes: number): string;
declare enum FlipDirection {
    Horizontal,

    Vertical,
}
/**
 * Resize filters
 */
declare enum ResizeFilter {
    Nearest,

    Linear,

    Cubic,

    Gaussian,

    Lanczos3,
}
/**
 * Interpolation algorithms used for rotations
 */
declare enum Interpolation {
    Nearest,

    Bilinear,

    Bicubic,
}
/**
 * Direction
 */
declare enum Direction {
    Press,

    Release,

    Click,
}
declare enum Key {
    /**
     * Top-row digit '0' key (not numpad)
     */
    Num0,

    /**
     * Top-row digit '1' key (not numpad)
     */
    Num1,

    /**
     * Top-row digit '2' key (not numpad)
     */
    Num2,

    /**
     * Top-row digit '3' key (not numpad)
     */
    Num3,

    /**
     * Top-row digit '4' key (not numpad)
     */
    Num4,

    /**
     * Top-row digit '5' key (not numpad)
     */
    Num5,

    /**
     * Top-row digit '6' key (not numpad)
     */
    Num6,

    /**
     * Top-row digit '7' key (not numpad)
     */
    Num7,

    /**
     * Top-row digit '8' key (not numpad)
     */
    Num8,

    /**
     * Top-row digit '9' key (not numpad)
     */
    Num9,

    /**
     * Letter key 'A'
     */
    A,

    /**
     * Letter key 'B'
     */
    B,

    /**
     * Letter key 'C'
     */
    C,

    /**
     * Letter key 'D'
     */
    D,

    /**
     * Letter key 'E'
     */
    E,

    /**
     * Letter key 'F'
     */
    F,

    /**
     * Letter key 'G'
     */
    G,

    /**
     * Letter key 'H'
     */
    H,

    /**
     * Letter key 'I'
     */
    I,

    /**
     * Letter key 'J'
     */
    J,

    /**
     * Letter key 'K'
     */
    K,

    /**
     * Letter key 'L'
     */
    L,

    /**
     * Letter key 'M'
     */
    M,

    /**
     * Letter key 'N'
     */
    N,

    /**
     * Letter key 'O'
     */
    O,

    /**
     * Letter key 'P'
     */
    P,

    /**
     * Letter key 'Q'
     */
    Q,

    /**
     * Letter key 'R'
     */
    R,

    /**
     * Letter key 'S'
     */
    S,

    /**
     * Letter key 'T'
     */
    T,

    /**
     * Letter key 'U'
     */
    U,

    /**
     * Letter key 'V'
     */
    V,

    /**
     * Letter key 'W'
     */
    W,

    /**
     * Letter key 'X'
     */
    X,

    /**
     * Letter key 'Y'
     */
    Y,

    /**
     * Letter key 'Z'
     */
    Z,

    /**
     * Brazilian ABNT keyboard key C1
     * @platform only works on Windows
     */
    AbntC1,

    /**
     * Brazilian ABNT keyboard key C2
     * @platform only works on Windows
     */
    AbntC2,

    /**
     * IME “Accept” / commit conversion
     * @platform only works on Windows
     */
    Accept,

    /**
     * Numpad '+' (addition) key
     */
    Add,

    /**
     * Alt (Alternate) modifier key
     */
    Alt,

    /**
     * Application/Menu key
     * @platform only works on Windows
     */
    Apps,

    /**
     * Attention key (legacy/rare)
     * @platform only works on Windows
     */
    Attention,

    /**
     * Backspace / Delete-previous-character
     */
    Backspace,

    /**
     * Break key (X11/Linux)
     * @platform only works on Linux
     */
    Break,

    /**
     * Begin key
     * @platform only works on Linux
     */
    Begin,

    /**
     * Browser Back
     * @platform only works on Windows
     */
    BrowserBack,

    /**
     * Browser Favorites
     * @platform only works on Windows
     */
    BrowserFavorites,

    /**
     * Browser Forward
     * @platform only works on Windows
     */
    BrowserForward,

    /**
     * Browser Home
     * @platform only works on Windows
     */
    BrowserHome,

    /**
     * Browser Refresh
     * @platform only works on Windows
     */
    BrowserRefresh,

    /**
     * Browser Search
     * @platform only works on Windows
     */
    BrowserSearch,

    /**
     * Browser Stop
     * @platform only works on Windows
     */
    BrowserStop,

    /**
     * Cancel key (legacy)
     */
    Cancel,

    /**
     * Caps Lock toggle
     */
    CapsLock,

    /**
     * Clear key
     */
    Clear,

    /**
     * Control (Ctrl) modifier key
     */
    Control,

    /**
     * IME Convert (start/confirm conversion)
     * @platform only works on Windows
     */
    Convert,

    /**
     * Cursor Select (CRSel)
     * @platform only works on Windows
     */
    CursorSelect,

    /**
     * IME: switch to alphanumeric
     * @platform only works on Windows
     */
    DbeAlphanumeric,

    /**
     * IME: code input mode
     * @platform only works on Windows
     */
    DbeCodeinput,

    /**
     * IME: determine string
     * @platform only works on Windows
     */
    DbeDetermineString,

    /**
     * IME: enter dialog conversion mode
     * @platform only works on Windows
     */
    DbeEnterDlgConversionMode,

    /**
     * IME: open configuration
     * @platform only works on Windows
     */
    DbeEnterImeConfigMode,

    /**
     * IME: word register mode
     * @platform only works on Windows
     */
    DbeEnterWordRegisterMode,

    /**
     * IME: flush/reset composition string
     * @platform only works on Windows
     */
    DbeFlushString,

    /**
     * IME: Hiragana
     * @platform only works on Windows
     */
    DbeHiragana,

    /**
     * IME: Katakana
     * @platform only works on Windows
     */
    DbeKatakana,

    /**
     * IME: no code point
     * @platform only works on Windows
     */
    DbeNoCodepoint,

    /**
     * IME: no roman
     * @platform only works on Windows
     */
    DbeNoRoman,

    /**
     * IME: Roman
     * @platform only works on Windows
     */
    DbeRoman,

    /**
     * IME: SBCS character
     * @platform only works on Windows
     */
    DbesbcsChar,

    /**
     * IME: SBCS/Special char
     * @platform only works on Windows
     */
    DbesChar,

    /**
     * Numpad decimal point '.'
     */
    Decimal,

    /**
     * Delete / Forward delete
     */
    Delete,

    /**
     * Numpad divide '/'
     */
    Divide,

    /**
     * Arrow: Down
     */
    DownArrow,

    /**
     * End key
     */
    End,

    /**
     * Erase EOF
     * @platform only works on Windows
     */
    Ereof,

    /**
     * Escape key
     */
    Escape,

    /**
     * Execute key
     */
    Execute,

    /**
     * Extend Selection (ExSel)
     * @platform only works on Windows
     */
    Exsel,

    /**
     * Function key F1
     */
    F1,

    /**
     * Function key F2
     */
    F2,

    /**
     * Function key F3
     */
    F3,

    /**
     * Function key F4
     */
    F4,

    /**
     * Function key F5
     */
    F5,

    /**
     * Function key F6
     */
    F6,

    /**
     * Function key F7
     */
    F7,

    /**
     * Function key F8
     */
    F8,

    /**
     * Function key F9
     */
    F9,

    /**
     * Function key F10
     */
    F10,

    /**
     * Function key F11
     */
    F11,

    /**
     * Function key F12
     */
    F12,

    /**
     * Function key F13
     */
    F13,

    /**
     * Function key F14
     */
    F14,

    /**
     * Function key F15
     */
    F15,

    /**
     * Function key F16
     */
    F16,

    /**
     * Function key F17
     */
    F17,

    /**
     * Function key F18
     */
    F18,

    /**
     * Function key F19
     */
    F19,

    /**
     * Function key F20
     */
    F20,

    /**
     * Function key F21
     */
    F21,

    /**
     * Function key F22
     */
    F22,

    /**
     * Function key F23
     */
    F23,

    /**
     * Function key F24
     */
    F24,

    /**
     * Function key F25
     * @platform only works on Linux
     */
    F25,

    /**
     * Function key F26
     * @platform only works on Linux
     */
    F26,

    /**
     * Function key F27
     * @platform only works on Linux
     */
    F27,

    /**
     * Function key F28
     * @platform only works on Linux
     */
    F28,

    /**
     * Function key F29
     * @platform only works on Linux
     */
    F29,

    /**
     * Function key F30
     * @platform only works on Linux
     */
    F30,

    /**
     * Function key F31
     * @platform only works on Linux
     */
    F31,

    /**
     * Function key F32
     * @platform only works on Linux
     */
    F32,

    /**
     * Function key F33
     * @platform only works on Linux
     */
    F33,

    /**
     * Function key F34
     * @platform only works on Linux
     */
    F34,

    /**
     * Function key F35
     * @platform only works on Linux
     */
    F35,

    /**
     * IME Final (end conversion)
     * @platform only works on Windows
     */
    Final,

    /**
     * Find key
     * @platform only works on Linux
     */
    Find,

    /**
     * Gamepad: A button
     * @platform only works on Windows
     */
    GamepadA,

    /**
     * Gamepad: B button
     * @platform only works on Windows
     */
    GamepadB,

    /**
     * Gamepad: D-Pad Down
     * @platform only works on Windows
     */
    GamepadDPadDown,

    /**
     * Gamepad: D-Pad Left
     * @platform only works on Windows
     */
    GamepadDPadLeft,

    /**
     * Gamepad: D-Pad Right
     * @platform only works on Windows
     */
    GamepadDPadRight,

    /**
     * Gamepad: D-Pad Up
     * @platform only works on Windows
     */
    GamepadDPadUp,

    /**
     * Gamepad: Left shoulder (L1)
     * @platform only works on Windows
     */
    GamepadLeftShoulder,

    /**
     * Gamepad: Left thumbstick button (L3)
     * @platform only works on Windows
     */
    GamepadLeftThumbstickButton,

    /**
     * Gamepad: Left thumbstick down
     * @platform only works on Windows
     */
    GamepadLeftThumbstickDown,

    /**
     * Gamepad: Left thumbstick left
     * @platform only works on Windows
     */
    GamepadLeftThumbstickLeft,

    /**
     * Gamepad: Left thumbstick right
     * @platform only works on Windows
     */
    GamepadLeftThumbstickRight,

    /**
     * Gamepad: Left thumbstick up
     * @platform only works on Windows
     */
    GamepadLeftThumbstickUp,

    /**
     * Gamepad: Left trigger (L2)
     * @platform only works on Windows
     */
    GamepadLeftTrigger,

    /**
     * Gamepad: Menu / Start
     * @platform only works on Windows
     */
    GamepadMenu,

    /**
     * Gamepad: Right shoulder (R1)
     * @platform only works on Windows
     */
    GamepadRightShoulder,

    /**
     * Gamepad: Right thumbstick button (R3)
     * @platform only works on Windows
     */
    GamepadRightThumbstickButton,

    /**
     * Gamepad: Right thumbstick down
     * @platform only works on Windows
     */
    GamepadRightThumbstickDown,

    /**
     * Gamepad: Right thumbstick left
     * @platform only works on Windows
     */
    GamepadRightThumbstickLeft,

    /**
     * Gamepad: Right thumbstick right
     * @platform only works on Windows
     */
    GamepadRightThumbstickRight,

    /**
     * Gamepad: Right thumbstick up
     * @platform only works on Windows
     */
    GamepadRightThumbstickUp,

    /**
     * Gamepad: Right trigger (R2)
     * @platform only works on Windows
     */
    GamepadRightTrigger,

    /**
     * Gamepad: View / Back
     * @platform only works on Windows
     */
    GamepadView,

    /**
     * Gamepad: X button
     * @platform only works on Windows
     */
    GamepadX,

    /**
     * Gamepad: Y button
     * @platform only works on Windows
     */
    GamepadY,

    /**
     * Hangeul toggle (Korean layout)
     * @platform only works on Windows
     */
    Hangeul,

    /**
     * Hangul toggle (Korean layout)
     */
    Hangul,

    /**
     * Hanja toggle (Chinese characters on Korean layout)
     */
    Hanja,

    /**
     * Help key
     */
    Help,

    /**
     * Home key
     */
    Home,

    /**
     * ICO (legacy) key 00
     * @platform only works on Windows
     */
    Ico00,

    /**
     * ICO (legacy) Clear
     * @platform only works on Windows
     */
    IcoClear,

    /**
     * ICO (legacy) Help
     * @platform only works on Windows
     */
    IcoHelp,

    /**
     * IME Off (disable IME)
     * @platform only works on Windows
     */
    ImeOff,

    /**
     * IME On (enable IME)
     * @platform only works on Windows
     */
    ImeOn,

    /**
     * Insert key
     */
    Insert,

    /**
     * IME: Junja mode
     * @platform only works on Windows
     */
    Junja,

    /**
     * IME: Kana mode
     * @platform only works on Windows
     */
    Kana,

    /**
     * Kanji toggle (Japanese layout)
     */
    Kanji,

    /**
     * Launch application 1
     * @platform only works on Windows
     */
    LaunchApp1,

    /**
     * Launch application 2
     * @platform only works on Windows
     */
    LaunchApp2,

    /**
     * Launch default mail client
     * @platform only works on Windows
     */
    LaunchMail,

    /**
     * Launch media selector
     * @platform only works on Windows
     */
    LaunchMediaSelect,

    /**
     * Left Control
     */
    LeftControl,

    /**
     * Arrow: Left
     */
    LeftArrow,

    /**
     * Line Feed key
     * @platform only works on Linux
     */
    Linefeed,

    /**
     * Left Alt/Menu
     */
    LeftAlt,

    /**
     * Left Shift
     */
    LeftShift,

    /**
     * Left Windows / Super key
     * @platform only works on Windows
     */
    LeftWindows,

    /**
     * Next media track
     */
    MediaNextTrack,

    /**
     * Play/Pause media
     */
    MediaPlayPause,

    /**
     * Previous media track
     */
    MediaPrevTrack,

    /**
     * Stop media
     */
    MediaStop,

    /**
     * Meta key (also known as "windows", "super", and "command")
     */
    Meta,

    /**
     * IME mode change
     */
    ModeChange,

    /**
     * Numpad multiply '*'
     */
    Multiply,

    /**
     * Navigation: Accept/OK (UWP)
     * @platform only works on Windows
     */
    NavigationAccept,

    /**
     * Navigation: Cancel/Back (UWP)
     * @platform only works on Windows
     */
    NavigationCancel,

    /**
     * Navigation: Down (UWP)
     * @platform only works on Windows
     */
    NavigationDown,

    /**
     * Navigation: Left (UWP)
     * @platform only works on Windows
     */
    NavigationLeft,

    /**
     * Navigation: Menu (UWP)
     * @platform only works on Windows
     */
    NavigationMenu,

    /**
     * Navigation: Right (UWP)
     * @platform only works on Windows
     */
    NavigationRight,

    /**
     * Navigation: Up (UWP)
     * @platform only works on Windows
     */
    NavigationUp,

    /**
     * Navigation: View (UWP)
     * @platform only works on Windows
     */
    NavigationView,

    /**
     * NoName key (reserved)
     * @platform only works on Windows
     */
    NoName,

    /**
     * IME Non-Convert (cancel conversion)
     * @platform only works on Windows
     */
    NonConvert,

    /**
     * Placeholder "no key"
     * @platform only works on Windows
     */
    None,

    /**
     * Num Lock toggle
     */
    Numlock,

    /**
     * Numpad digit '0'
     */
    Numpad0,

    /**
     * Numpad digit '1'
     */
    Numpad1,

    /**
     * Numpad digit '2'
     */
    Numpad2,

    /**
     * Numpad digit '3'
     */
    Numpad3,

    /**
     * Numpad digit '4'
     */
    Numpad4,

    /**
     * Numpad digit '5'
     */
    Numpad5,

    /**
     * Numpad digit '6'
     */
    Numpad6,

    /**
     * Numpad digit '7'
     */
    Numpad7,

    /**
     * Numpad digit '8'
     */
    Numpad8,

    /**
     * Numpad digit '9'
     */
    Numpad9,

    /**
     * Numpad Enter
     */
    NumpadEnter,

    /**
     * OEM specific key 1
     * @platform only works on Windows
     */
    Oem1,

    /**
     * OEM specific key 102 (angle bracket/pipe on some layouts)
     * @platform only works on Windows
     */
    Oem102,

    /**
     * OEM specific key 2
     * @platform only works on Windows
     */
    Oem2,

    /**
     * OEM specific key 3 (backtick/tilde on some layouts)
     * @platform only works on Windows
     */
    Oem3,

    /**
     * OEM specific key 4 (left bracket on some layouts)
     * @platform only works on Windows
     */
    Oem4,

    /**
     * OEM specific key 5 (right bracket on some layouts)
     * @platform only works on Windows
     */
    Oem5,

    /**
     * OEM specific key 6 (semicolon on some layouts)
     * @platform only works on Windows
     */
    Oem6,

    /**
     * OEM specific key 7 (quote on some layouts)
     * @platform only works on Windows
     */
    Oem7,

    /**
     * OEM specific key 8
     * @platform only works on Windows
     */
    Oem8,

    /**
     * OEM Attention
     * @platform only works on Windows
     */
    OemAttn,

    /**
     * OEM Auto
     * @platform only works on Windows
     */
    OemAuto,

    /**
     * OEM Ax
     * @platform only works on Windows
     */
    OemAx,

    /**
     * OEM Backtab (reverse Tab)
     * @platform only works on Windows
     */
    OemBacktab,

    /**
     * OEM Clear
     * @platform only works on Windows
     */
    OemClear,

    /**
     * OEM Comma ','
     * @platform only works on Windows
     */
    OemComma,

    /**
     * OEM Copy
     * @platform only works on Windows
     */
    OemCopy,

    /**
     * OEM Cusel
     * @platform only works on Windows
     */
    OemCusel,

    /**
     * OEM Enlw
     * @platform only works on Windows
     */
    OemEnlw,

    /**
     * OEM Finish
     * @platform only works on Windows
     */
    OemFinish,

    /**
     * OEM FJ Jisho (dictionary)
     * @platform only works on Windows
     */
    OemfjJisho,

    /**
     * OEM FJ Loya
     * @platform only works on Windows
     */
    OemfjLoya,

    /**
     * OEM FJ Masshou
     * @platform only works on Windows
     */
    OemfjMasshou,

    /**
     * OEM FJ Roya
     * @platform only works on Windows
     */
    OemfjRoya,

    /**
     * OEM FJ Touroku
     * @platform only works on Windows
     */
    OemfjTouroku,

    /**
     * OEM Jump
     * @platform only works on Windows
     */
    OemJump,

    /**
     * OEM Minus '-'
     * @platform only works on Windows
     */
    OemMinus,

    /**
     * OEM NEC Equal '='
     * @platform only works on Windows
     */
    OemnecEqual,

    /**
     * OEM PA1
     * @platform only works on Windows
     */
    Oempa1,

    /**
     * OEM PA2
     * @platform only works on Windows
     */
    Oempa2,

    /**
     * OEM PA3
     * @platform only works on Windows
     */
    Oempa3,

    /**
     * OEM Period '.'
     * @platform only works on Windows
     */
    OemPeriod,

    /**
     * OEM Plus '+'
     * @platform only works on Windows
     */
    OemPlus,

    /**
     * OEM Reset
     * @platform only works on Windows
     */
    OemReset,

    /**
     * OEM Wsctrl
     * @platform only works on Windows
     */
    OemWsctrl,

    /**
     * Same as Alt
     */
    Option,

    /**
     * PA1 key
     * @platform only works on Windows
     */
    Pa1,

    /**
     * Packet key (used to pass Unicode chars)
     * @platform only works on Windows
     */
    Packet,

    /**
     * Page Down
     */
    PageDown,

    /**
     * Page Up
     */
    PageUp,

    /**
     * Pause key
     */
    Pause,

    /**
     * Media Play
     * @platform only works on Windows
     */
    Play,

    /**
     * Screenshot
     */
    PrintScreen,

    /**
     * IME Process key
     * @platform only works on Windows
     */
    Processkey,

    /**
     * Right Control
     */
    RightControl,

    /**
     * Redo
     * @platform only works on Linux
     */
    Redo,

    /**
     * Enter / Return
     */
    Return,

    /**
     * Arrow: Right
     */
    RightArrow,

    /**
     * Right Alt/Menu
     * @platform only works on Windows
     */
    RightAlt,

    /**
     * Right Shift
     */
    RightShift,

    /**
     * Right Windows / Super key
     * @platform only works on Windows
     */
    RightWindows,

    /**
     * Scroll key (legacy)
     * @platform only works on Windows
     */
    Scroll,

    /**
     * Scroll Lock
     * @platform only works on Linux
     */
    ScrollLock,

    /**
     * Select key
     */
    Select,

    /**
     * Script switch
     * @platform only works on Linux
     */
    ScriptSwitch,

    /**
     * Numpad separator (locale-dependent)
     * @platform only works on Windows
     */
    Separator,

    /**
     * Shift modifier
     */
    Shift,

    /**
     * Shift Lock
     * @platform only works on Linux
     */
    ShiftLock,

    /**
     * System Sleep
     * @platform only works on Windows
     */
    Sleep,

    /**
     * Spacebar
     */
    Space,

    /**
     * Numpad '-' (subtract)
     */
    Subtract,

    /**
     * System Request (SysRq)
     * @platform only works on Linux
     */
    SysReq,

    /**
     * Tab / focus next
     */
    Tab,

    /**
     * Undo
     * @platform only works on Linux
     */
    Undo,

    /**
     * Arrow: Up
     */
    UpArrow,

    /**
     * Volume down
     */
    VolumeDown,

    /**
     * Volume mute
     */
    VolumeMute,

    /**
     * Volume up
     */
    VolumeUp,

    /**
     * Microphone mute
     * @platform only works on Linux
     */
    MicrophoneMute,

    /**
     * Zoom key
     * @platform only works on Windows
     */
    Zoom,
}
declare enum KeyError {
    Unsupported,
}
/**
 * Process status
 */
declare enum ProcessStatus {
    Idle,

    Run,

    Sleep,

    Stop,

    Zombie,

    Tracing,

    Dead,

    Wakekill,

    Waking,

    Parked,

    LockBlocked,

    UninterruptibleDiskSleep,

    Unknown,
}
/**
 * Disk kind
 */
declare enum DiskKind {
    /**
     * Hard disk drive
     */
    Hdd,

    /**
     * Solid-state drive
     */
    Ssd,

    /**
     * Unknown drive kind
     */
    Unknown,
}
/**
 * Should the script wait at the end of the execution?
 * @defaultValue `WaitAtEnd.Automatic`
 */
declare enum WaitAtEnd {
    /**
     * Automatically decide if the script should wait.
     * Setting hotstrings will have the script wait.
     */
    Automatic,

    /**
     * Always wait.
     */
    Yes,

    /**
     * Never wait.
     */
    No,
}
declare enum ClipboardMode {
    Clipboard,

    /**
     * @platform only works on Linux
     */
    Selection,
}
/**
 * Mouse button.
 */
declare enum Button {
    /**
     * Left button
     */
    Left,

    /**
     * Middle button
     */
    Middle,

    /**
     * Right button
     */
    Right,

    /**
     * Back button
     */
    Back,

    /**
     * Forward button
     */
    Forward,
}
declare enum Axis {
    Horizontal,

    Vertical,
}
/**
 * Tweening functions for smooth movement.
 */
declare enum Tween {
    /**
     * Starts slowly, then accelerates with an overshoot.
     */
    BackIn,

    /**
     * Starts and ends with an overshoot, accelerating in between.
     */
    BackInOut,

    /**
     * Starts quickly, then decelerates with an overshoot.
     */
    BackOut,

    /**
     * Starts by bouncing off the start point.
     */
    BounceIn,

    /**
     * Bounces at both the start and end points.
     */
    BounceInOut,

    /**
     * Ends with a bounce effect.
     */
    BounceOut,

    /**
     * Starts slowly and accelerates in a circular motion.
     */
    CircIn,

    /**
     * Starts and ends slowly with a circular motion.
     */
    CircInOut,

    /**
     * Ends slowly with a circular motion.
     */
    CircOut,

    /**
     * Starts slowly and accelerates cubically.
     */
    CubicIn,

    /**
     * Starts and ends slowly with a cubic acceleration.
     */
    CubicInOut,

    /**
     * Ends slowly with a cubic deceleration.
     */
    CubicOut,

    /**
     * Starts with an elastic effect, overshooting the target.
     */
    ElasticIn,

    /**
     * Starts and ends with an elastic effect.
     */
    ElasticInOut,

    /**
     * Ends with an elastic effect, overshooting the target.
     */
    ElasticOut,

    /**
     * Starts slowly and accelerates exponentially.
     */
    ExpoIn,

    /**
     * Starts and ends slowly with an exponential acceleration.
     */
    ExpoInOut,

    /**
     * Ends slowly with an exponential deceleration.
     */
    ExpoOut,

    /**
     * A linear tween with no acceleration or deceleration.
     */
    Linear,

    /**
     * Starts slowly and accelerates quadratically.
     */
    QuadIn,

    /**
     * Starts and ends slowly with a quadratic acceleration.
     */
    QuadInOut,

    /**
     * Ends slowly with a quadratic deceleration.
     */
    QuadOut,

    /**
     * Starts slowly and accelerates quartically.
     */
    QuartIn,

    /**
     * Starts and ends slowly with a quartic acceleration.
     */
    QuartInOut,

    /**
     * Ends slowly with a quartic deceleration.
     */
    QuartOut,

    /**
     * Starts slowly and accelerates quintically.
     */
    QuintIn,

    /**
     * Starts and ends slowly with a quintic acceleration.
     */
    QuintInOut,

    /**
     * Ends slowly with a quintic deceleration.
     */
    QuintOut,

    /**
     * Starts slowly and accelerates sinusoidally.
     */
    SineIn,

    /**
     * Starts and ends slowly with a sinusoidal acceleration.
     */
    SineInOut,

    /**
     * Ends slowly with a sinusoidal deceleration.
     */
    SineOut,
}
declare enum MessageBoxIcon {
    Info,

    Warning,

    Error,
}
declare enum MessageBoxResult {
    Yes,

    No,

    Ok,

    Cancel,
}
declare enum Method {
    Get,

    Post,

    Put,

    Delete,

    Head,

    Options,

    Connect,

    Patch,

    Trace,
}
declare interface App {
    /**
     * Should the app wait at the end of execution
     */
    waitAtEnd: WaitAtEnd | boolean;
    /**
     * Version of Actiona-cli
     */
    readonly version: string;
    /**
     * Executable path
     */
    readonly executablePath: string;
    /**
     * All environment variables
     */
    readonly env: Record<string, string>;
    /**
     * Current working directory
     */
    readonly cwd: string;
    /**
     * Sets the current working directory
     */
    setCwd(cwd: string): void;
}
declare const app: App;
declare interface Audio {
    playFile(path: string, options?: PlaySoundOptions): PlayingSound;
    playFileAndWait(path: string, options?: PlaySoundOptions): Promise<void>;
}
declare const audio: Audio;
/**
 * PlayingSound
 */
declare interface PlayingSound {
    /**
     * Sound volume
     * @defaultValue `1`
     */
    volume: number;
    /**
     * Sound playing speed
     * @defaultValue `1`
     */
    playbackRate: number;
    /**
     * Promise allowing to wait until the sound has finished playing
     */
    readonly finished: Promise<void>;
    /**
     * The duration of the sound in seconds
     */
    readonly duration?: number;
    /**
     * Is the sound paused
     */
    readonly paused: boolean;
    pause(): void;
    resume(): void;
    stop(): void;
}
declare interface Clipboard {
    /**
     * Image operations
     */
    readonly image: ClipboardImage;
    /**
     * File list operations
     */
    readonly fileList: ClipboardFileList;
    /**
     * Text operations
     */
    readonly text: ClipboardText;
    /**
     * Html operations
     */
    readonly html: ClipboardHtml;
    clear(mode?: ClipboardMode): Promise<void>;
}
declare const clipboard: Clipboard;
/**
 * ClipboardImage
 */
declare interface ClipboardImage {
    set(image: Image, mode?: ClipboardMode): Promise<void>;
    get(mode?: ClipboardMode): Promise<Image>;
}
/**
 * ClipboardFileList
 */
declare interface ClipboardFileList {
    get(mode?: ClipboardMode): Promise<string[]>;
}
/**
 * ClipboardText
 */
declare interface ClipboardText {
    set(text: string, mode?: ClipboardMode): Promise<void>;
    get(mode?: ClipboardMode): Promise<string>;
}
/**
 * ClipboardHtml
 */
declare interface ClipboardHtml {
    set(html: string, altText?: string, mode?: ClipboardMode): Promise<void>;
    get(mode?: ClipboardMode): Promise<string>;
}
declare class Image {
    /**
     * Creates a new empty image.
     * 
     * Example
     * ```js
     * let image = new Image(100, 100);
     * ```
     */
    constructor(width: number, height: number);
    static fromBytes(bytes: Uint8Array): Image;
    save(path: string): void;
    static load(path: string): Image;
    equals(other: Image): boolean;
    toString(): string;
    clone(): Image;
    /**
     * Invert the colors of this image.
     */
    invert(): this;
    /**
     * Invert the colors of this image and returns a new image.
     */
    inverted(): Image;
    /**
     * Blur the image.
     */
    blur(options?: BlurOptions): this;
    /**
     * Blur the image and returns a new image.
     */
    blurred(options?: BlurOptions): Image;
    /**
     * Rotate the image.
     */
    rotate(angle: number, options?: RotationOptions): this;
    /**
     * Rotate the image and returns a new image.
     */
    rotated(angle: number, options?: RotationOptions): Image;
    /**
     * Flip the image.
     */
    flip(flipDirection: FlipDirection): this;
    /**
     * Flip the image and returns a new image.
     */
    flipped(flipDirection: FlipDirection): Image;
    /**
     * Hue rotate the image.
     */
    hueRotate(value: number): this;
    /**
     * Hue rotate the image and returns a new image.
     */
    hueRotated(value: number): Image;
    /**
     * Transform this image into a grayscale.
     */
    grayscale(): this;
    /**
     * Returns a grayscale version of this image.
     */
    grayscaled(): Image;
    /**
     * Crops this image.
     */
    crop(rect: RectLike): this;
    /**
     * Crops this image.
     */
    crop(r: RectLike): this;
    /**
     * Returns a cropped version of this image.
     */
    cropped(rect: RectLike): Image;
    /**
     * Returns a cropped version of this image.
     */
    cropped(r: RectLike): Image;
    /**
     * Resizes this image.
     */
    resize(width: number, height: number, options?: ResizeOptions): this;
    /**
     * Returns a resized version of this image.
     */
    resized(width: number, height: number, options?: ResizeOptions): Image;
    /**
     * Brightens or darkens the pixels of this image.
     */
    adjustBrightness(value: number): this;
    /**
     * Returns a brightened or darkened version of this image.
     */
    adjustedBrightness(value: number): Image;
    /**
     * Adjusts the contrast of this image.
     */
    adjustContrast(value: number): this;
    /**
     * Returns a new image with an adjusted contrast.
     */
    adjustedContrast(value: number): Image;
    /**
     * Fill this image with a color.
     */
    fill(color: ColorLike): this;
    /**
     * Fill this image with a color.
     */
    fill(c: ColorLike): this;
    /**
     * Fill this image with a color.
     */
    filled(color: ColorLike): Image;
    /**
     * Fill this image with a color.
     */
    filled(c: ColorLike): Image;
    /**
     * Returns the value of a pixel.
     */
    getPixel(position: PointLike): Color;
    /**
     * Returns the value of a pixel.
     */
    getPixel(x: number, y: number): Color;
    /**
     * Returns the value of a pixel.
     */
    setPixel(position: PointLike, color: ColorLike): this;
    /**
     * Returns the value of a pixel.
     */
    setPixel(position: PointLike, c: ColorLike): this;
    /**
     * Returns the value of a pixel.
     */
    setPixel(x: number, y: number, color: ColorLike): this;
    /**
     * Returns the value of a pixel.
     */
    setPixel(x: number, y: number, c: ColorLike): this;
    /**
     * Creates a new image from a part of this image.
     */
    copyRegion(rect: RectLike): Image;
    /**
     * Creates a new image from a part of this image.
     */
    copyRegion(r: RectLike): Image;
    /**
     * Returns a Rect representing this image.
     */
    rect(): Rect;
    /**
     * Draw a cross on this image.
     */
    drawCross(position: PointLike, color: ColorLike): this;
    /**
     * Draw a cross on this image.
     */
    drawCross(position: PointLike, c: ColorLike): this;
    /**
     * Draw a cross on this image.
     */
    drawCross(x: number, y: number, color: ColorLike): this;
    /**
     * Draw a cross on this image.
     */
    drawCross(x: number, y: number, c: ColorLike): this;
    /**
     * Draw a cross on a copy of this image.
     */
    withCross(position: PointLike, color: ColorLike): Image;
    /**
     * Draw a cross on a copy of this image.
     */
    withCross(position: PointLike, c: ColorLike): Image;
    /**
     * Draw a cross on a copy of this image.
     */
    withCross(x: number, y: number, color: ColorLike): Image;
    /**
     * Draw a cross on a copy of this image.
     */
    withCross(x: number, y: number, c: ColorLike): Image;
    /**
     * Draw a line on this image.
     */
    drawLine(start: PointLike, end: PointLike, color: ColorLike): this;
    /**
     * Draw a line on this image.
     */
    drawLine(start: PointLike, end: PointLike, c: ColorLike): this;
    /**
     * Draw a line on this image.
     */
    drawLine(start: PointLike, x: number, y: number, color: ColorLike): this;
    /**
     * Draw a line on this image.
     */
    drawLine(start: PointLike, x: number, y: number, c: ColorLike): this;
    /**
     * Draw a line on this image.
     */
    drawLine(x: number, y: number, end: PointLike, color: ColorLike): this;
    /**
     * Draw a line on this image.
     */
    drawLine(x: number, y: number, end: PointLike, c: ColorLike): this;
    /**
     * Draw a line on this image.
     */
    drawLine(x1: number, y1: number, x2: number, y2: number, color: ColorLike): this;
    /**
     * Draw a line on this image.
     */
    drawLine(x1: number, y1: number, x2: number, y2: number, c: ColorLike): this;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(start: PointLike, end: PointLike, color: ColorLike): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(start: PointLike, end: PointLike, c: ColorLike): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(start: PointLike, x: number, y: number, color: ColorLike): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(start: PointLike, x: number, y: number, c: ColorLike): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(x: number, y: number, end: PointLike, color: ColorLike): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(x: number, y: number, end: PointLike, c: ColorLike): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(x1: number, y1: number, x2: number, y2: number, color: ColorLike): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(x1: number, y1: number, x2: number, y2: number, c: ColorLike): Image;
    /**
     * Draw a circle on this image.
     */
    drawCircle(center: PointLike, radius: number, color: ColorLike, options?: DrawingOptions): this;
    /**
     * Draw a circle on this image.
     */
    drawCircle(center: PointLike, radius: number, c: ColorLike, options?: DrawingOptions): this;
    /**
     * Draw a circle on this image.
     */
    drawCircle(x: number, y: number, radius: number, color: ColorLike, options?: DrawingOptions): this;
    /**
     * Draw a circle on this image.
     */
    drawCircle(x: number, y: number, radius: number, c: ColorLike, options?: DrawingOptions): this;
    /**
     * Draw a circle on a copy of this image.
     */
    withCircle(center: PointLike, radius: number, color: ColorLike, options?: DrawingOptions): Image;
    /**
     * Draw a circle on a copy of this image.
     */
    withCircle(center: PointLike, radius: number, c: ColorLike, options?: DrawingOptions): Image;
    /**
     * Draw a circle on a copy of this image.
     */
    withCircle(x: number, y: number, radius: number, color: ColorLike, options?: DrawingOptions): Image;
    /**
     * Draw a circle on a copy of this image.
     */
    withCircle(x: number, y: number, radius: number, c: ColorLike, options?: DrawingOptions): Image;
    /**
     * Draw an ellipse on this image.
     */
    drawEllipse(center: PointLike, widthRadius: number, heightRadius: number, color: ColorLike, options?: DrawingOptions): this;
    /**
     * Draw an ellipse on this image.
     */
    drawEllipse(center: PointLike, widthRadius: number, heightRadius: number, c: ColorLike, options?: DrawingOptions): this;
    /**
     * Draw an ellipse on this image.
     */
    drawEllipse(x: number, y: number, widthRadius: number, heightRadius: number, color: ColorLike, options?: DrawingOptions): this;
    /**
     * Draw an ellipse on this image.
     */
    drawEllipse(x: number, y: number, widthRadius: number, heightRadius: number, c: ColorLike, options?: DrawingOptions): this;
    /**
     * Draw an ellipse on a copy of this image.
     */
    withEllipse(center: PointLike, widthRadius: number, heightRadius: number, color: ColorLike, options?: DrawingOptions): Image;
    /**
     * Draw an ellipse on a copy of this image.
     */
    withEllipse(center: PointLike, widthRadius: number, heightRadius: number, c: ColorLike, options?: DrawingOptions): Image;
    /**
     * Draw an ellipse on a copy of this image.
     */
    withEllipse(x: number, y: number, widthRadius: number, heightRadius: number, color: ColorLike, options?: DrawingOptions): Image;
    /**
     * Draw an ellipse on a copy of this image.
     */
    withEllipse(x: number, y: number, widthRadius: number, heightRadius: number, c: ColorLike, options?: DrawingOptions): Image;
    /**
     * Draw a rectangle on this image.
     */
    drawRectangle(rect: RectLike, color: ColorLike, options?: DrawingOptions): this;
    /**
     * Draw a rectangle on this image.
     */
    drawRectangle(rect: RectLike, c: ColorLike, options?: DrawingOptions): this;
    /**
     * Draw a rectangle on this image.
     */
    drawRectangle(r: RectLike, color: ColorLike, options?: DrawingOptions): this;
    /**
     * Draw a rectangle on this image.
     */
    drawRectangle(r: RectLike, c: ColorLike, options?: DrawingOptions): this;
    /**
     * Draw a rectangle on a copy of this image.
     */
    withRectangle(rect: RectLike, color: ColorLike, options?: DrawingOptions): Image;
    /**
     * Draw a rectangle on a copy of this image.
     */
    withRectangle(rect: RectLike, c: ColorLike, options?: DrawingOptions): Image;
    /**
     * Draw a rectangle on a copy of this image.
     */
    withRectangle(r: RectLike, color: ColorLike, options?: DrawingOptions): Image;
    /**
     * Draw a rectangle on a copy of this image.
     */
    withRectangle(r: RectLike, c: ColorLike, options?: DrawingOptions): Image;
    /**
     * Draw another image on this image.
     */
    drawImage(position: PointLike, image: Image, options?: DrawImageOptions): this;
    /**
     * Draw another image on this image.
     */
    drawImage(x: number, y: number, image: Image, options?: DrawImageOptions): this;
    /**
     * Draw another image on a copy of this image.
     */
    withImage(position: PointLike, image: Image, options?: DrawImageOptions): Image;
    /**
     * Draw another image on a copy of this image.
     */
    withImage(x: number, y: number, image: Image, options?: DrawImageOptions): Image;
    /**
     * TODO
     */
    findImage(Image: Image, options?: FindImageOptions): void;
    height(): number;
    width(): number;
}
/**
 * A Color.
 * 
 * 
 * 
 * 
 * ```js
 * let c = new Color(128, 255, 255, 255);
 * ```
 */
declare class Color {
    /**
     * #FF0000FF
     */
    static readonly Red: Color;
    /**
     * #008000FF
     */
    static readonly Green: Color;
    /**
     * #0000FFFF
     */
    static readonly Blue: Color;
    /**
     * #FFFFFFFF
     */
    static readonly White: Color;
    /**
     * #000000FF
     */
    static readonly Black: Color;
    /**
     * #00000000
     */
    static readonly Transparent: Color;
    /**
     * #F0F8FFFF
     */
    static readonly AliceBlue: Color;
    /**
     * #FAEBD7FF
     */
    static readonly AntiqueWhite: Color;
    /**
     * #00FFFFFF
     */
    static readonly Aqua: Color;
    /**
     * #7FFFD4FF
     */
    static readonly Aquamarine: Color;
    /**
     * #F0FFFFFF
     */
    static readonly Azure: Color;
    /**
     * #F5F5DCFF
     */
    static readonly Beige: Color;
    /**
     * #FFE4C4FF
     */
    static readonly Bisque: Color;
    /**
     * #FFEBCDFF
     */
    static readonly BlanchedAlmond: Color;
    /**
     * #8A2BE2FF
     */
    static readonly BlueViolet: Color;
    /**
     * #A52A2AFF
     */
    static readonly Brown: Color;
    /**
     * #DEB887FF
     */
    static readonly BurlyWood: Color;
    /**
     * #5F9EA0FF
     */
    static readonly CadetBlue: Color;
    /**
     * #7FFF00FF
     */
    static readonly Chartreuse: Color;
    /**
     * #D2691EFF
     */
    static readonly Chocolate: Color;
    /**
     * #FF7F50FF
     */
    static readonly Coral: Color;
    /**
     * #6495EDFF
     */
    static readonly CornflowerBlue: Color;
    /**
     * #FFF8DCFF
     */
    static readonly Cornsilk: Color;
    /**
     * #DC143CFF
     */
    static readonly Crimson: Color;
    /**
     * #00FFFFFF
     */
    static readonly Cyan: Color;
    /**
     * #00008BFF
     */
    static readonly DarkBlue: Color;
    /**
     * #008B8BFF
     */
    static readonly DarkCyan: Color;
    /**
     * #B8860BFF
     */
    static readonly DarkGoldenRod: Color;
    /**
     * #A9A9A9FF
     */
    static readonly DarkGray: Color;
    /**
     * #006400FF
     */
    static readonly DarkGreen: Color;
    /**
     * #BDB76BFF
     */
    static readonly DarkKhaki: Color;
    /**
     * #8B008BFF
     */
    static readonly DarkMagenta: Color;
    /**
     * #556B2FFF
     */
    static readonly DarkOliveGreen: Color;
    /**
     * #FF8C00FF
     */
    static readonly DarkOrange: Color;
    /**
     * #9932CCFF
     */
    static readonly DarkOrchid: Color;
    /**
     * #8B0000FF
     */
    static readonly DarkRed: Color;
    /**
     * #E9967AFF
     */
    static readonly DarkSalmon: Color;
    /**
     * #8FBC8FFF
     */
    static readonly DarkSeaGreen: Color;
    /**
     * #483D8BFF
     */
    static readonly DarkSlateBlue: Color;
    /**
     * #2F4F4FFF
     */
    static readonly DarkSlateGray: Color;
    /**
     * #00CED1FF
     */
    static readonly DarkTurquoise: Color;
    /**
     * #9400D3FF
     */
    static readonly DarkViolet: Color;
    /**
     * #FF1493FF
     */
    static readonly DeepPink: Color;
    /**
     * #00BFFFFF
     */
    static readonly DeepSkyBlue: Color;
    /**
     * #696969FF
     */
    static readonly DimGray: Color;
    /**
     * #1E90FFFF
     */
    static readonly DodgerBlue: Color;
    /**
     * #B22222FF
     */
    static readonly Firebrick: Color;
    /**
     * #FFFAF0FF
     */
    static readonly FloralWhite: Color;
    /**
     * #228B22FF
     */
    static readonly ForestGreen: Color;
    /**
     * #FF00FFFF
     */
    static readonly Fuchsia: Color;
    /**
     * #DCDCDCFF
     */
    static readonly Gainsboro: Color;
    /**
     * #F8F8FFFF
     */
    static readonly GhostWhite: Color;
    /**
     * #FFD700FF
     */
    static readonly Gold: Color;
    /**
     * #DAA520FF
     */
    static readonly GoldenRod: Color;
    /**
     * #808080FF
     */
    static readonly Gray: Color;
    /**
     * #ADFF2FFF
     */
    static readonly GreenYellow: Color;
    /**
     * #F0FFF0FF
     */
    static readonly HoneyDew: Color;
    /**
     * #FF69B4FF
     */
    static readonly HotPink: Color;
    /**
     * #CD5C5CFF
     */
    static readonly IndianRed: Color;
    /**
     * #4B0082FF
     */
    static readonly Indigo: Color;
    /**
     * #FFFFF0FF
     */
    static readonly Ivory: Color;
    /**
     * #F0E68CFF
     */
    static readonly Khaki: Color;
    /**
     * #E6E6FAFF
     */
    static readonly Lavender: Color;
    /**
     * #FFF0F5FF
     */
    static readonly LavenderBlush: Color;
    /**
     * #7CFC00FF
     */
    static readonly LawnGreen: Color;
    /**
     * #FFFACDFF
     */
    static readonly LemonChiffon: Color;
    /**
     * #ADD8E6FF
     */
    static readonly LightBlue: Color;
    /**
     * #F08080FF
     */
    static readonly LightCoral: Color;
    /**
     * #E0FFFFFF
     */
    static readonly LightCyan: Color;
    /**
     * #FAFAD2FF
     */
    static readonly LightGoldenRodYellow: Color;
    /**
     * #D3D3D3FF
     */
    static readonly LightGray: Color;
    /**
     * #90EE90FF
     */
    static readonly LightGreen: Color;
    /**
     * #FFB6C1FF
     */
    static readonly LightPink: Color;
    /**
     * #FFA07AFF
     */
    static readonly LightSalmon: Color;
    /**
     * #20B2AAFF
     */
    static readonly LightSeaGreen: Color;
    /**
     * #87CEFAFF
     */
    static readonly LightSkyBlue: Color;
    /**
     * #778899FF
     */
    static readonly LightSlateGray: Color;
    /**
     * #B0C4DEFF
     */
    static readonly LightSteelBlue: Color;
    /**
     * #FFFFE0FF
     */
    static readonly LightYellow: Color;
    /**
     * #00FF00FF
     */
    static readonly Lime: Color;
    /**
     * #32CD32FF
     */
    static readonly LimeGreen: Color;
    /**
     * #FAF0E6FF
     */
    static readonly Linen: Color;
    /**
     * #FF00FFFF
     */
    static readonly Magenta: Color;
    /**
     * #800000FF
     */
    static readonly Maroon: Color;
    /**
     * #66CDAAFF
     */
    static readonly MediumAquaMarine: Color;
    /**
     * #0000CDFF
     */
    static readonly MediumBlue: Color;
    /**
     * #BA55D3FF
     */
    static readonly MediumOrchid: Color;
    /**
     * #9370DBFF
     */
    static readonly MediumPurple: Color;
    /**
     * #3CB371FF
     */
    static readonly MediumSeaGreen: Color;
    /**
     * #7B68EEFF
     */
    static readonly MediumSlateBlue: Color;
    /**
     * #00FA9AFF
     */
    static readonly MediumSpringGreen: Color;
    /**
     * #48D1CCFF
     */
    static readonly MediumTurquoise: Color;
    /**
     * #C71585FF
     */
    static readonly MediumVioletRed: Color;
    /**
     * #191970FF
     */
    static readonly MidnightBlue: Color;
    /**
     * #F5FFFAFF
     */
    static readonly MintCream: Color;
    /**
     * #FFE4E1FF
     */
    static readonly MistyRose: Color;
    /**
     * #FFE4B5FF
     */
    static readonly Moccasin: Color;
    /**
     * #FFDEADFF
     */
    static readonly NavajoWhite: Color;
    /**
     * #000080FF
     */
    static readonly Navy: Color;
    /**
     * #FDF5E6FF
     */
    static readonly OldLace: Color;
    /**
     * #808000FF
     */
    static readonly Olive: Color;
    /**
     * #6B8E23FF
     */
    static readonly OliveDrab: Color;
    /**
     * #FFA500FF
     */
    static readonly Orange: Color;
    /**
     * #FF4500FF
     */
    static readonly OrangeRed: Color;
    /**
     * #DA70D6FF
     */
    static readonly Orchid: Color;
    /**
     * #EEE8AAFF
     */
    static readonly PaleGoldenRod: Color;
    /**
     * #98FB98FF
     */
    static readonly PaleGreen: Color;
    /**
     * #AFEEEEFF
     */
    static readonly PaleTurquoise: Color;
    /**
     * #DB7093FF
     */
    static readonly PaleVioletRed: Color;
    /**
     * #FFEFD5FF
     */
    static readonly PapayaWhip: Color;
    /**
     * #FFDAB9FF
     */
    static readonly PeachPuff: Color;
    /**
     * #CD853FFF
     */
    static readonly Peru: Color;
    /**
     * #FFC0CBFF
     */
    static readonly Pink: Color;
    /**
     * #DDA0DDFF
     */
    static readonly Plum: Color;
    /**
     * #B0E0E6FF
     */
    static readonly PowderBlue: Color;
    /**
     * #800080FF
     */
    static readonly Purple: Color;
    /**
     * #663399FF
     */
    static readonly RebeccaPurple: Color;
    /**
     * #BC8F8FFF
     */
    static readonly RosyBrown: Color;
    /**
     * #4169E1FF
     */
    static readonly RoyalBlue: Color;
    /**
     * #8B4513FF
     */
    static readonly SaddleBrown: Color;
    /**
     * #FA8072FF
     */
    static readonly Salmon: Color;
    /**
     * #F4A460FF
     */
    static readonly SandyBrown: Color;
    /**
     * #2E8B57FF
     */
    static readonly SeaGreen: Color;
    /**
     * #FFF5EEFF
     */
    static readonly SeaShell: Color;
    /**
     * #A0522DFF
     */
    static readonly Sienna: Color;
    /**
     * #C0C0C0FF
     */
    static readonly Silver: Color;
    /**
     * #87CEEBFF
     */
    static readonly SkyBlue: Color;
    /**
     * #6A5ACDFF
     */
    static readonly SlateBlue: Color;
    /**
     * #708090FF
     */
    static readonly SlateGray: Color;
    /**
     * #FFFAFAFF
     */
    static readonly Snow: Color;
    /**
     * #00FF7FFF
     */
    static readonly SpringGreen: Color;
    /**
     * #4682B4FF
     */
    static readonly SteelBlue: Color;
    /**
     * #D2B48CFF
     */
    static readonly Tan: Color;
    /**
     * #008080FF
     */
    static readonly Teal: Color;
    /**
     * #D8BFD8FF
     */
    static readonly Thistle: Color;
    /**
     * #FF6347FF
     */
    static readonly Tomato: Color;
    /**
     * #40E0D0FF
     */
    static readonly Turquoise: Color;
    /**
     * #EE82EEFF
     */
    static readonly Violet: Color;
    /**
     * #F5DEB3FF
     */
    static readonly Wheat: Color;
    /**
     * #F5F5F5FF
     */
    static readonly WhiteSmoke: Color;
    /**
     * #FFFF00FF
     */
    static readonly Yellow: Color;
    /**
     * #9ACD32FF
     */
    static readonly YellowGreen: Color;
    /**
     * Red (should be between 0-255)
     */
    r: number;
    /**
     * Green (should be between 0-255)
     */
    g: number;
    /**
     * Blue (should be between 0-255)
     */
    b: number;
    /**
     * Alpha (should be between 0-255)
     */
    a: number;
    /**
     * Constructor with three color channels and an alpha channel.
     */
    constructor(r: number, g: number, b: number, a?: number);
    /**
     * Constructor with anything Color-like.
     */
    constructor(c: ColorLike);
    equals(other: Color): boolean;
    toString(): string;
    clone(): Color;
}
declare interface Console {
    print(...args: unknown[]): void;
    printLn(...args: unknown[]): void;
    log(...args: unknown[]): void;
    info(...args: unknown[]): void;
    warn(...args: unknown[]): void;
    error(...args: unknown[]): void;
    clear(): void;
    time(label?: string): void;
    timeEnd(label?: string): void;
    count(label?: string): void;
}
declare const console: Console;
/**
 * Directory entry
 */
declare interface DirectoryEntry {
    readonly isFile: boolean;
    readonly path: string;
    readonly isDirectory: boolean;
    readonly size: number;
    readonly isSymlink: boolean;
    readonly fileName: string;
}
/**
 * Directory options
 */
declare interface DirectoryOptions {
    /**
     * Should the directories be created or removed recursively?
     * @defaultValue `true`
     */
    recursive?: boolean;
}
/**
 * Directory list options
 */
declare interface DirectoryListOptions {
    /**
     * Should the entries be sorted?
     * @defaultValue `true`
     */
    sort?: boolean;
    /**
     * Should each entry's absolute path be computed?
     * @defaultValue `true`
     */
    absolutePath?: boolean;
    /**
     * Should each entry's size be fetched?
     * @defaultValue `true`
     */
    fetchSize?: boolean;
}
declare class Directory {
    private constructor();
    static create(path: string, options?: DirectoryOptions): Promise<void>;
    static remove(path: string, options?: DirectoryOptions): Promise<void>;
    static listEntries(path: string, options?: DirectoryListOptions): Promise<DirectoryEntry[]>;
}
declare interface Displays {
    randomPoint(): Promise<Point>;
    fromPoint(point: PointLike): Promise<DisplayInfo | undefined>;
    fromPoint(x: number, y: number): Promise<DisplayInfo | undefined>;
    fromName(name: NameLike): Promise<DisplayInfo | undefined>;
    fromDeviceName(name: NameLike): Promise<DisplayInfo | undefined>;
    fromId(id: number): Promise<DisplayInfo | undefined>;
    smallest(): Promise<DisplayInfo | undefined>;
    largest(): Promise<DisplayInfo | undefined>;
}
declare const displays: Displays;
/**
 * A 2D Point.
 * 
 * 
 * ```js
 * let p = new Point(1, 2);
 * ```
 */
declare class Point {
    /**
     * X coordinate
     */
    x: number;
    /**
     * Y coordinate
     */
    y: number;
    /**
     * Constructor with two numbers.
     */
    constructor(x: number, y: number);
    /**
     * Constructor with anything Point-like.
     */
    constructor(p: PointLike);
    /**
     * Length of this point.
     */
    length(): number;
    /**
     * Returns a random point around this point.
     */
    static randomInCircle(center: PointLike, radius: number): Point;
    /**
     * Returns a random point around this point.
     */
    static randomInCircle(x: number, y: number, radius: number): Point;
    /**
     * Calculates the distance between this point and another.
     */
    distanceTo(other: Point): number;
    /**
     * Returns a JSON representation of this Point.
     */
    toJson(): string;
    /**
     * Returns true if this Point is at the origin, (0, 0).
     */
    isOrigin(): boolean;
    /**
     * Computes the distance between two points.
     */
    static distance(a: Point, b: Point): number;
    /**
     * Returns true if a Point equals another.
     */
    equals(other: Point): boolean;
    /**
     * Adds two points and returns a new Point.
     */
    add(other: Point): Point;
    /**
     * Subtracts two points and returns a new Point.
     */
    subtract(other: Point): Point;
    /**
     * Scales this point by a factor and returns a new Point.
     */
    scaled(factor: number): Point;
    /**
     * Returns a string representation of this Point.
     */
    toString(): string;
    /**
     * Clones this Point.
     */
    clone(): Point;
}
/**
 * Display info
 */
declare interface DisplayInfo {
    /**
     * The display pixel height
     */
    readonly heightMm: number;
    /**
     * The display name
     */
    readonly name: string;
    /**
     * The display pixel width
     */
    readonly widthMm: number;
    /**
     * The display rectangle
     */
    readonly rect: Rect;
    /**
     * The display rotation: can be 0, 90, 180, 270 and represents the screen rotation in clock-wise degrees
     */
    readonly rotation: number;
    /**
     * Output device's pixel scale factor
     */
    readonly scaleFactor: number;
    /**
     * The display refresh rate
     */
    readonly frequency: number;
    /**
     * Whether the screen is the main screen
     */
    readonly isPrimary: boolean;
    /**
     * The display friendly name
     */
    readonly friendlyName: string;
    /**
     * Unique identifier associated with the display
     */
    readonly id: number;
}
declare class Rect {
    /**
     * Constructor with a position and a size.
     */
    constructor(x: number, y: number, width: number, height: number);
    /**
     * Constructor with anything Rect-like.
     */
    constructor(r: RectLike);
    equals(other: Rect): boolean;
    contains(point: Point): boolean;
    toString(): string;
    clone(): Rect;
    intersects(other: Rect): boolean;
    intersection(other: Rect): Rect | undefined;
    union(other: Rect): Rect;
}
/**
 * File open options
 */
declare interface OpenOptions {
    /**
     * Should the file be opened with read access?
     * @defaultValue `true`
     */
    read?: boolean;
    /**
     * Should the file be opened with write access?
     * @defaultValue `false`
     */
    write?: boolean;
    /**
     * Writing: open the file in append mode.
     * Note that setting this to `true` implies setting `write` to `true`.
     * @defaultValue `false`
     */
    append?: boolean;
    /**
     * Writing: truncate (remove all contents of) the file.
     * Note that this only works if `write` is `true`.
     * @defaultValue `false`
     */
    truncate?: boolean;
    /**
     * Writing: create a new file if it doesn't exist.
     * Note that this only works if `write` or `append` are set to `true`.
     * @defaultValue `false`
     */
    create?: boolean;
    /**
     * Writing: always create a new file, even if one already exists.
     * Note that this only works if `write` or `append` are set to `true`.
     * Note that `create` and `truncate` are ignored if this is set to `true`.
     * @defaultValue `false`
     */
    createNew?: boolean;
}
/**
 * File represents a file handle.
 */
declare class File {
    /**
     * The file path
     */
    readonly path: string;
    private constructor();
    /**
     * Opens a file.
     * 
     * Example
     * ```js
     * // Open a file for reading
     * let file = await File.open("my_file.txt", {
     * read: true,
     * });
     * 
     * // Create a new file for writing.
     * let file = await File.open("my_file.txt", {
     * write: true,
     * createNew: true,
     * });
     * 
     * // Append to an existing file.
     * let file = await File.open("my_file.txt", {
     * write: true,
     * append: true,
     * });
     * ```
     */
    static open(path: string, options?: OpenOptions): Promise<File>;
    /**
     * Returns true if the file is open.
     */
    isOpen(): boolean;
    /**
     * Closes this file handle.
     * Please note that the actual file might not be closed until all other handles to it are also closed.
     * This can happen if you cloned() this File.
     */
    close(): void;
    writeBytes(bytes: Uint8Array): Promise<void>;
    static writeBytes(path: string, bytes: Uint8Array): Promise<void>;
    writeText(text: string): Promise<void>;
    static writeText(path: string, text: string): Promise<void>;
    readBytes(amount?: number): Promise<Uint8Array>;
    static readBytes(path: string, amount?: number): Promise<Uint8Array>;
    readText(): Promise<string>;
    static readText(path: string): Promise<string>;
    size(): Promise<number>;
    setSize(size: number): Promise<void>;
    readonly(): Promise<boolean>;
    setReadonly(readonly: boolean): Promise<void>;
    /**
     * @platform does not work on Windows
     */
    mode(): Promise<number>;
    /**
     * Sets the file mode.
     * You should use the octal notation to specify the mode: `await file.setMode(0o445)`.
     * @platform does not work on Windows
     */
    setMode(mode: number): Promise<void>;
    modifiedTime(): Promise<Date>;
    setModifiedTime(date: Date): Promise<void>;
    accessedTime(): Promise<Date>;
    setAccessedTime(date: Date): Promise<void>;
    creationTime(): Promise<Date>;
    /**
     * @platform does not work on Linux
     */
    setCreationTime(date: Date): Promise<void>;
    position(): Promise<number>;
    setPosition(position: number): Promise<void>;
    setRelativePosition(offset: number): Promise<void>;
    rewind(): Promise<void>;
    static exists(path: string): Promise<boolean>;
    /**
     * Removes a file from the filesystem.
     * 
     * Note that there is no guarantee that the file is immediately deleted (e.g. depending on platform, other open file descriptors may prevent immediate removal).
     */
    static remove(path: string): Promise<void>;
    static copy(source: string, destination: string): Promise<void>;
    static rename(source: string, destination: string): Promise<void>;
    static move(source: string, destination: string): Promise<void>;
    clone(): File;
    equals(other: File): boolean;
    toString(): string;
}
declare class Filesystem {
    private constructor();
    static exists(path: string): Promise<boolean>;
    static isFile(path: string): Promise<boolean>;
    static isDirectory(path: string): Promise<boolean>;
    static isSymlink(path: string): Promise<boolean>;
}
declare interface Hotstrings {
    add(source: string, replacement: string | (() => string | Promise<string>) | Image | (() => Image | Promise<Image>), options?: HotstringOptions): void;
    remove(source: string): void;
}
declare const hotstrings: Hotstrings;
/**
 * Resize options
 */
declare interface ResizeOptions {
    /**
     * Should the aspect ratio be kept?
     * @defaultValue `false`
     */
    keepAspectRatio?: boolean;
    /**
     * What filter to use
     * @defaultValue `ResizeFilter.Cubic`
     */
    filter?: ResizeFilter;
}
/**
 * Blur options
 */
declare interface BlurOptions {
    /**
     * Perform a fast, lower quality blur
     * @defaultValue `false`
     */
    fast?: boolean;
    /**
     * Standard deviation of the (approximated) Gaussian
     * @defaultValue `2`
     */
    sigma?: number;
}
/**
 * Draw image options
 */
declare interface DrawImageOptions {
    /**
     * Source rectangle.
     * `undefined` means the whole image.
     * @defaultValue `undefined`
     */
    sourceRect?: Rect;
}
/**
 * Rotation options
 */
declare interface RotationOptions {
    /**
     * Interpolation algorithm (used if the rotation angle is different from 90, 180, and 270 degrees and no center position has been set)
     * @defaultValue `Interpolation.Bilinear`
     */
    interpolation?: Interpolation;
    /**
     * Rotation center
     * @defaultValue image center
     */
    center?: Point;
    /**
     * Default color, used if the rotation triggers more pixels to be displayed
     * @defaultValue `Color.Black`
     */
    defaultColor?: Color;
}
/**
 * Drawing options
 */
declare interface DrawingOptions {
    /**
     * Draw a hollow shape instead of a filled one
     * @defaultValue `false`
     */
    hollow?: boolean;
}
declare class AbortSignal {
    private constructor();
}
declare class AbortController {
    readonly signal: AbortSignal;
    constructor();
    abort(): void;
}
declare interface Keyboard {
    text(text: string): Promise<void>;
    key(key: Key | string | number, direction: Direction): Promise<void>;
    raw(keycode: number, direction: Direction): Promise<void>;
    isKeyPressed(key: Key | string | number): Promise<boolean>;
    waitForKeys(keys: (Key | string | number)[], exclusive?: boolean): Promise<void>;
}
declare const keyboard: Keyboard;
declare interface Mouse {
    /**
     * @platform does not work on Wayland
     */
    isPressed(button: Button): Promise<boolean>;
    scroll(length: number, axis?: Axis): Promise<void>;
    /**
     * @platform does not work on Wayland
     */
    position(): Promise<Point>;
    measureSpeed(duration?: number): Promise<number>;
    move(point: PointLike, options?: MoveOptions): Task<void>;
    move(x: number, y: number, options?: MoveOptions): Task<void>;
    setPosition(point: PointLike): Promise<void>;
    setPosition(x: number, y: number): Promise<void>;
    setRelativePosition(point: PointLike): Promise<void>;
    setRelativePosition(x: number, y: number): Promise<void>;
    click(options?: ClickOptions): Promise<void>;
    doubleClick(options?: DoubleClickOptions): Promise<void>;
    press(options?: PressOptions): Promise<void>;
    release(button?: Button): Promise<void>;
}
declare const mouse: Mouse;
declare interface Random {
    /**
     * Returns a number between 0 (inclusive) and 1 (exclusive)
     */
    number(): number;
    /**
     * Returns a number between 0 (inclusive) and max (exclusive)
     */
    number(max: number): number;
    /**
     * Returns a number between min (inclusive) and max (exclusive)
     */
    number(min: number, max: number): number;
    /**
     * Returns an integer between 0 (inclusive) and max (inclusive)
     */
    integer(max: number): number;
    /**
     * Returns an integer between min (inclusive) and max (inclusive)
     */
    integer(min: number, max: number): number;
    /**
     * Sets the seed to a value.
     * This seed is used for all random number generation. Since the random number generator is
     * deterministic that means that setting it to a particular number will always generate the same
     * random numbers.
     */
    setSeed(seed: number): void;
    /**
     * Resets the seed to be a random one.
     */
    resetSeed(): void;
    /**
     * Returns a random position on any display.
     */
    position(): Promise<Point>;
    /**
     * Chooses one random entry in an array.
     * A fallback can be provided, in case the array is empty.
     */
    choice<T>(array: Array<T>, fallback?: T): T;
}
declare const random: Random;
declare interface Screenshot {
}
declare const screenshot: Screenshot;
declare interface StandardPaths {
    /**
     * Music directory
     */
    readonly music?: string;
    /**
     * Pictures directory
     */
    readonly pictures?: string;
    /**
     * Desktop directory
     */
    readonly desktop?: string;
    /**
     * Cache directory
     */
    readonly cache?: string;
    /**
     * Local config directory
     */
    readonly localConfig?: string;
    /**
     * Config directory
     */
    readonly config?: string;
    /**
     * Videos directory
     */
    readonly videos?: string;
    /**
     * Downloads directory
     */
    readonly downloads?: string;
    /**
     * Home directory
     */
    readonly home?: string;
    /**
     * Public directory
     */
    readonly public?: string;
    /**
     * Documents directory
     */
    readonly documents?: string;
    toString(): string;
}
declare const standard_paths: StandardPaths;
/**
 * System
 */
declare interface System {
    /**
     * Hardware information
     */
    readonly hardware: Hardware;
    /**
     * Memory information
     */
    readonly memory: Memory;
    /**
     * Network information
     */
    readonly network: Network;
    /**
     * Processes information
     */
    readonly processes: Processes;
    /**
     * Cpu information
     */
    readonly cpu: Cpu;
    /**
     * Storage information
     */
    readonly storage: Storage;
    /**
     * Os information
     */
    readonly os: Os;
    shutdown(force?: boolean): void;
    reboot(force?: boolean): void;
    logout(force?: boolean): void;
    hibernate(): void;
    sleep(): void;
    open(path: string, withApp?: string): void;
    openPath(path: string, withApp?: string): void;
}
declare const system: System;
declare class Ui {
    private constructor();
    static messageBox(text: string, options?: MessageBoxOptions): Promise<MessageBoxResult>;
}
declare const ui: Ui;
declare interface Web {
    /**
     * Downloads a binary file.
     */
    download(url: string, options?: WebOptions): ProgressTask<Uint8Array, WebProgress>;
    /**
     * Downloads a text file.
     */
    downloadText(url: string, options?: WebOptions): ProgressTask<string, WebProgress>;
    /**
     * Downloads an image.
     */
    downloadImage(url: string, options?: WebOptions): ProgressTask<Image, WebProgress>;
    /**
     * Downloads a file to a directory.
     */
    downloadFile(url: string, directory?: string, options?: WebOptions): ProgressTask<string, WebProgress>;
}
declare const web: Web;
declare class Wildcard {
    /**
     * Constructor.
     */
    constructor(pattern: string);
}
declare class Path {
    private constructor();
    static join(...args: string[]): string;
    static filename(path: string): string;
    static basename(path: string): string;
    static parent(path: string): string;
    static dirname(path: string): string;
    static isAbsolute(path: string): boolean;
    static isRelative(path: string): boolean;
    static extension(path: string): string;
    static extname(path: string): string;
    static setExtension(path: string, extension: string): string;
}
/**
 * A size.
 * 
 * 
 * ```js
 * let p = new Size(1, 2);
 * ```
 */
declare class Size {
    /**
     * width
     */
    width: number;
    /**
     * height
     */
    height: number;
    /**
     * Constructor with two numbers.
     */
    constructor(width: number, height: number);
    /**
     * Constructor with anything Size-like.
     */
    constructor(s: SizeLike);
    /**
     * Returns a JSON representation of this Size.
     */
    toJson(): string;
    /**
     * Returns true if a Size equals another.
     */
    equals(other: Size): boolean;
    /**
     * Adds two sizes and returns a new Size.
     */
    add(other: Size): Size;
    /**
     * Subtracts two sizes and returns a new Size.
     */
    subtract(other: Size): Size;
    /**
     * Scales this size by a factor and returns a new Size.
     */
    scale(factor: number): Size;
    /**
     * Returns a string representation of this Size.
     */
    toString(): string;
    /**
     * Clones this Size.
     */
    clone(): Size;
}
declare class MessageBoxButtons {
    private constructor();
    static ok(): MessageBoxButtons;
    static okCustom(okLabel: string): MessageBoxButtons;
    static okCancel(): MessageBoxButtons;
    static okCancelCustom(okLabel: string, cancelLabel: string): MessageBoxButtons;
    static yesNo(): MessageBoxButtons;
    static yesNoCancel(): MessageBoxButtons;
    static yesNoCancelCustom(yesLabel: string, noLabel: string, cancelLabel: string): MessageBoxButtons;
}
/**
 * Multipart form
 */
declare interface MultipartForm {
}
declare class WebProgress {
    private constructor();
    current(): number;
    total(): number;
    finished(): boolean;
}
/**
 * Cpu
 */
declare interface Cpu {
    /**
     * Architecture
     */
    readonly architecture: string;
    /**
     * Logical core count
     */
    readonly logicalCoreCount: number;
    /**
     * Physical core count
     */
    readonly physicalCoreCount?: number;
    usage(): Promise<number>;
    coreUsage(logicalCoreIndex: number): Promise<number>;
    frequencies(): Promise<number[]>;
    toString(): string;
}
/**
 * Hardware
 */
declare interface Hardware {
    /**
     * Motherboard
     */
    readonly motherboard: Motherboard;
    /**
     * Family
     */
    readonly family?: string;
    /**
     * Stock keeping unit
     */
    readonly stockKeepingUnit?: string;
    /**
     * Version
     */
    readonly version?: string;
    /**
     * Serial number
     */
    readonly serialNumber?: string;
    /**
     * Name
     */
    readonly name?: string;
    /**
     * Uuid
     */
    readonly uuid?: string;
    /**
     * Vendor name
     */
    readonly vendorName?: string;
    /**
     * Hardware components
     */
    listComponents(options?: ListComponentsOptions): Promise<Component[]>;
    toString(): string;
}
declare interface Motherboard {
    /**
     * Asset tag
     */
    readonly assetTag?: string;
    /**
     * Name
     */
    readonly name?: string;
    /**
     * Vendor name
     */
    readonly vendorName?: string;
    /**
     * Version
     */
    readonly version?: string;
    /**
     * Serial number
     */
    readonly serialNumber?: string;
    toString(): string;
}
declare interface Component {
    /**
     * Critical temperature
     */
    readonly criticalTemperature?: number;
    /**
     * ID
     */
    readonly id?: string;
    /**
     * Label
     */
    readonly label: string;
    /**
     * Temperature
     */
    readonly temperature?: number;
    /**
     * Maximum temperature
     */
    readonly maxTemperature?: number;
    toString(): string;
}
/**
 * Memory
 */
declare interface Memory {
    /**
     * CGroup limits
     * @platform only works on Linux
     */
    readonly cgroupLimits?: CGroupLimits;
    /**
     * Memory usage
     */
    usage(): Promise<MemoryUsage>;
    /**
     * Swap usage
     */
    swapUsage(): Promise<MemoryUsage>;
    toString(): string;
}
declare interface MemoryUsage {
    /**
     * Free
     */
    readonly free: number;
    /**
     * Available
     */
    readonly available: number;
    /**
     * Total
     */
    readonly total: number;
    /**
     * Used
     */
    readonly used: number;
    toString(): string;
}
/**
 * CGroup limits
 * @platform only works on Linux
 */
declare interface CGroupLimits {
    /**
     * Free memory
     */
    readonly freeMemory: number;
    /**
     * Free swap
     */
    readonly freeSwap: number;
    /**
     * Total memory
     */
    readonly totalMemory: number;
    /**
     * RSS
     */
    readonly rss: number;
    toString(): string;
}
/**
 * Network
 */
declare interface Network {
    /**
     * Host name
     */
    readonly hostname?: string;
    /**
     * Interfaces
     */
    listInterfaces(options?: ListInterfacesOptions): Promise<NetworkInterface[]>;
    toString(): string;
}
declare interface NetworkInterface {
    /**
     * Inbound
     */
    readonly inbound: Traffic;
    /**
     * MAC address
     */
    readonly macAddress?: string;
    /**
     * Outbound
     */
    readonly outbound: Traffic;
    /**
     * MTU
     */
    readonly mtu: number;
    /**
     * Name
     */
    readonly name: string;
    /**
     * Subnets
     */
    readonly subnets: string[];
    toString(): string;
}
declare interface Counters {
    /**
     * Data
     */
    readonly data: number;
    /**
     * Packets
     */
    readonly packets: number;
    /**
     * Errors
     */
    readonly errors: number;
    toString(): string;
}
declare interface Traffic {
    /**
     * Total
     */
    readonly total: Counters;
    /**
     * Delta
     */
    readonly delta: Counters;
    toString(): string;
}
/**
 * Os
 */
declare interface Os {
    /**
     * Distribution ID like
     */
    readonly distributionIdLike: string[];
    /**
     * Version
     */
    readonly version?: string;
    /**
     * Distribution ID
     */
    readonly distributionId: string;
    /**
     * Boot time
     */
    readonly bootTime: Date;
    /**
     * Name
     */
    readonly name?: string;
    /**
     * Kernel version
     */
    readonly kernelVersion?: string;
    /**
     * Uptime in seconds
     */
    readonly uptime: number;
    /**
     * Long version
     */
    readonly longVersion?: string;
    /**
     * Open files limit
     */
    readonly openFilesLimit?: number;
    /**
     * Kernel long version
     */
    readonly kernelLongVersion: string;
    /**
     * Users
     */
    listUsers(): Promise<User[]>;
    /**
     * Groups
     */
    listGroups(): Promise<Group[]>;
    toString(): string;
}
declare interface User {
    /**
     * Group name
     * @platform does not work on Windows
     */
    readonly groupName?: string;
    /**
     * Name
     */
    readonly name: string;
    /**
     * Group names
     */
    readonly groupNames: string[];
    /**
     * Group ID
     * @platform does not work on Windows
     */
    readonly groupId?: number;
    /**
     * ID
     */
    readonly id: string;
    /**
     * Groups
     */
    readonly groups: number[];
    toString(): string;
}
declare interface Group {
    /**
     * ID
     */
    readonly id: number;
    /**
     * Name
     */
    readonly name: string;
    toString(): string;
}
/**
 * Processes
 */
declare interface Processes {
    /**
     * Lists all processes
     */
    list(options?: ListProcessesOptions): Promise<Process[]>;
    toString(): string;
}
declare interface Process {
    /**
     * Cwd
     */
    readonly cwd?: string;
    /**
     * Exe
     */
    readonly exe?: string;
    /**
     * Disk usage
     */
    readonly diskUsage: DiskUsage;
    /**
     * Cmd
     */
    readonly cmd: string[];
    /**
     * Env
     */
    readonly env: string[];
    /**
     * Memory
     */
    readonly memory: number;
    /**
     * Virtual memory
     */
    readonly virtualMemory: number;
    /**
     * CPU usage
     */
    readonly cpuUsage: number;
    /**
     * Parent
     */
    readonly parent?: number;
    /**
     * Run time in seconds
     */
    readonly runTime: number;
    /**
     * Start time
     */
    readonly startTime: Object;
    /**
     * Group ID
     * @platform only works on Linux
     */
    readonly groupId?: number;
    /**
     * Session ID
     */
    readonly sessionId?: number;
    /**
     * Open files
     */
    readonly openFiles?: number;
    /**
     * Accumulated CPU time in seconds
     */
    readonly accumulatedCpuTime: number;
    /**
     * Status
     */
    readonly status: ProcessStatus;
    /**
     * User ID
     */
    readonly userId?: string;
    /**
     * Exists
     */
    readonly exists: boolean;
    /**
     * Root
     */
    readonly root?: string;
    /**
     * Name
     */
    readonly name?: string;
    /**
     * Pid
     */
    readonly pid: number;
    /**
     * Effective group ID
     * @platform only works on Linux
     */
    readonly effectiveGroupId?: number;
    /**
     * Open files limit
     */
    readonly openFilesLimit?: number;
    /**
     * Effective user ID
     * @platform only works on Linux
     */
    readonly effectiveUserId?: string;
    toString(): string;
}
/**
 * Storage
 */
declare interface Storage {
    /**
     * Disks
     */
    listDisks(options?: ListDisksOptions): Promise<Disk[]>;
    toString(): string;
}
declare interface Disk {
    /**
     * Is read-only
     */
    readonly isReadOnly: boolean;
    /**
     * Is removable
     */
    readonly isRemovable: boolean;
    /**
     * Usage
     */
    readonly usage: DiskUsage;
    /**
     * Name
     */
    readonly name?: string;
    /**
     * Available space
     */
    readonly availableSpace: number;
    /**
     * Kind
     */
    readonly kind: DiskKind;
    /**
     * File system
     */
    readonly fileSystem?: string;
    /**
     * Total space
     */
    readonly totalSpace: number;
    /**
     * Mount point
     */
    readonly mountPoint: string;
    toString(): string;
}
declare interface IoStats {
    /**
     * Delta
     */
    readonly delta: number;
    /**
     * Total
     */
    readonly total: number;
    toString(): string;
}
declare interface DiskUsage {
    /**
     * Written
     */
    readonly written: IoStats;
    /**
     * Read
     */
    readonly read: IoStats;
    toString(): string;
}
declare interface Concurrency {
    race<T>(promises: Iterable<T|PromiseLike<T>>): Task<Awaited<T>>;
}
/**
 * List components options
 */
declare interface ListComponentsOptions {
    /**
     * Rescan
     * @defaultValue `true`
     */
    rescan?: boolean;
}
/**
 * List network interfaces options
 */
declare interface ListInterfacesOptions {
    /**
     * Rescan
     * @defaultValue `true`
     */
    rescan?: boolean;
}
/**
 * List processes options
 */
declare interface ListProcessesOptions {
    /**
     * Rescan
     * @defaultValue `true`
     */
    rescan?: boolean;
}
/**
 * List disks options
 */
declare interface ListDisksOptions {
    /**
     * Rescan
     * @defaultValue `true`
     */
    rescan?: boolean;
}
/**
 * Web options
 */
declare interface WebOptions {
    /**
     * @defaultValue `undefined`
     */
    signal?: AbortSignal;
    /**
     * @defaultValue `undefined`
     */
    userName?: string;
    /**
     * @defaultValue `undefined`
     */
    password?: string;
    /**
     * @defaultValue `undefined`
     */
    headers?: Record<string, string>;
    /**
     * @defaultValue `Method.Get`
     */
    method?: Method;
    /**
     * @defaultValue `undefined`
     */
    timeout?: number;
    /**
     * Sets the content-type header.
     * Overrides any content-type set by other fields.
     * @defaultValue `undefined`
     */
    contentType?: string;
    /**
     * Form data as strings.
     * Sets content-type to "application/x-www-form-urlencoded".
     * @defaultValue `undefined`
     */
    form?: Record<string, string>;
    /**
     * Additional query parameters.
     * @defaultValue `undefined`
     */
    query?: Record<string, string>;
    /**
     * Form multipart data.
     * Sets content-type and content-length appropriately.
     * @defaultValue `undefined`
     */
    multipart?: MultipartForm;
}
/**
 * Play sound options
 */
declare interface PlaySoundOptions {
    /**
     * Volume to play the sound at
     * @defaultValue `1.0`
     */
    volume?: number;
    /**
     * Speed to play the sound at
     * @defaultValue `1.0`
     */
    playbackRate?: number;
    /**
     * Should the sound start paused
     * @defaultValue `false`
     */
    paused?: boolean;
    /**
     * Should the sound loop
     * @defaultValue `false`
     */
    loop?: boolean;
    /**
     * Fade in duration
     * @defaultValue `0`
     */
    fadeIn?: number;
    /**
     * Fade out duration
     * @defaultValue `0`
     */
    fadeOut?: number;
}
/**
 * Hotstring options
 */
declare interface HotstringOptions {
    /**
     * Erase the key first before replacing it with the replacement content.
     * @defaultValue `true`
     */
    eraseKey?: boolean;
    /**
     * When replacing with text, save it to the clipboard then simulate Ctrl+V to paste.
     * Replacing with an image always uses the clipboard.
     * @defaultValue `false`
     */
    useClipboardForText?: boolean;
    /**
     * Try to save and restore the clipboard's contents.
     * @defaultValue `true`
     */
    saveRestoreClipboard?: boolean;
}
/**
 * Find image options
 */
declare interface FindImageOptions {
}
/**
 * Move options
 */
declare interface MoveOptions {
    /**
     * @defaultValue `2000`
     */
    speed?: number;
    /**
     * @defaultValue `Tween.SineOut`
     */
    tween?: Tween;
    /**
     * @defaultValue `50`
     */
    perlinScale?: number;
    /**
     * @defaultValue `5`
     */
    perlinAmplitude?: number;
    /**
     * @defaultValue `0`
     */
    targetRandomness?: number;
    /**
     * Interval in seconds
     * @defaultValue `0.01`
     */
    interval?: number;
}
/**
 * Button click options
 */
declare interface ClickOptions extends PressOptions {
    /**
     * @defaultValue `1`
     */
    amount?: number;
    /**
     * @defaultValue `0`
     */
    interval?: number;
    /**
     * @defaultValue `0`
     */
    duration?: number;
}
/**
 * Button double click options
 */
declare interface DoubleClickOptions extends ClickOptions {
    /**
     * @defaultValue `0.25`
     */
    delay?: number;
}
/**
 * Button press options
 */
declare interface PressOptions {
    /**
     * @defaultValue `Button.Left`
     */
    button?: Button;
    /**
     * @defaultValue `undefined`
     */
    position?: Point;
    /**
     * @defaultValue `false`
     */
    relativePosition?: boolean;
}
/**
 * Message box options
 */
declare interface MessageBoxOptions {
    /**
     * @defaultValue `undefined`
     */
    title?: string;
    /**
     * @defaultValue `MessageBoxButtons.ok()`
     */
    buttons?: MessageBoxButtons;
    /**
     * @defaultValue `MessageBoxIcon.Info`
     */
    icon?: MessageBoxIcon;
}
