/**
 * Generated by doc-generator 0.1.0. DO NOT EDIT.
 */

/**
 * Task: cancellable promise.
 */
type Task<Result> = Promise<Result> & {
    cancel(): void;
};

/**
 * ProgressTask: task with progress.
 */
type ProgressTask<Result, Progress> = Task<Result> & {
    [Symbol.asyncIterator](): AsyncIterator<Progress>;
};
/**
 * Pauses the execution.
 */
declare function sleep(ms: number): Task<void>;
/**
 * Stops the execution.
 */
declare function exit(): void;
declare enum FlipDirection {
    Horizontal,

    Vertical,
}
/**
 * Resize filters
 */
declare enum ResizeFilter {
    Nearest,

    Linear,

    Cubic,

    Gaussian,

    Lanczos3,
}
/**
 * Interpolation algorithms used for rotations
 */
declare enum Interpolation {
    Nearest,

    Bilinear,

    Bicubic,
}
declare enum ClipboardMode {
    Clipboard,

    /**
     * @platform only works on Linux
     */
    Selection,
}
declare enum Key {
    Alt,

    Backspace,

    Cancel,

    CapsLock,

    Clear,

    Control,

    Delete,

    DownArrow,

    End,

    Escape,

    Execute,

    F1,

    F2,

    F3,

    F4,

    F5,

    F6,

    F7,

    F8,

    F9,

    F10,

    F11,

    F12,

    F13,

    F14,

    F15,

    F16,

    F17,

    F18,

    F19,

    F20,

    F21,

    F22,

    F23,

    F24,

    Hangul,

    Hanja,

    Help,

    Home,

    Insert,

    Kanji,

    LControl,

    LeftArrow,

    LMenu,

    LShift,

    MediaNextTrack,

    MediaPlayPause,

    MediaPrevTrack,

    MediaStop,

    Meta,

    ModeChange,

    Numlock,

    Option,

    PageDown,

    PageUp,

    Pause,

    PrintScr,

    RControl,

    Return,

    RightArrow,

    RShift,

    Select,

    Shift,

    Space,

    Tab,

    UpArrow,

    VolumeDown,

    VolumeMute,

    VolumeUp,

    Windows,
}
/**
 * Mouse button.
 */
declare enum Button {
    /**
     * Left button
     */
    Left,

    /**
     * Middle button
     */
    Middle,

    /**
     * Right button
     */
    Right,

    /**
     * Back button
     */
    Back,

    /**
     * Forward button
     */
    Forward,
}
declare enum Axis {
    Horizontal,

    Vertical,
}
/**
 * Tweening functions for smooth movement.
 */
declare enum Tween {
    /**
     * Starts slowly, then accelerates with an overshoot.
     */
    BackIn,

    /**
     * Starts and ends with an overshoot, accelerating in between.
     */
    BackInOut,

    /**
     * Starts quickly, then decelerates with an overshoot.
     */
    BackOut,

    /**
     * Starts by bouncing off the start point.
     */
    BounceIn,

    /**
     * Bounces at both the start and end points.
     */
    BounceInOut,

    /**
     * Ends with a bounce effect.
     */
    BounceOut,

    /**
     * Starts slowly and accelerates in a circular motion.
     */
    CircIn,

    /**
     * Starts and ends slowly with a circular motion.
     */
    CircInOut,

    /**
     * Ends slowly with a circular motion.
     */
    CircOut,

    /**
     * Starts slowly and accelerates cubically.
     */
    CubicIn,

    /**
     * Starts and ends slowly with a cubic acceleration.
     */
    CubicInOut,

    /**
     * Ends slowly with a cubic deceleration.
     */
    CubicOut,

    /**
     * Starts with an elastic effect, overshooting the target.
     */
    ElasticIn,

    /**
     * Starts and ends with an elastic effect.
     */
    ElasticInOut,

    /**
     * Ends with an elastic effect, overshooting the target.
     */
    ElasticOut,

    /**
     * Starts slowly and accelerates exponentially.
     */
    ExpoIn,

    /**
     * Starts and ends slowly with an exponential acceleration.
     */
    ExpoInOut,

    /**
     * Ends slowly with an exponential deceleration.
     */
    ExpoOut,

    /**
     * A linear tween with no acceleration or deceleration.
     */
    Linear,

    /**
     * Starts slowly and accelerates quadratically.
     */
    QuadIn,

    /**
     * Starts and ends slowly with a quadratic acceleration.
     */
    QuadInOut,

    /**
     * Ends slowly with a quadratic deceleration.
     */
    QuadOut,

    /**
     * Starts slowly and accelerates quartically.
     */
    QuartIn,

    /**
     * Starts and ends slowly with a quartic acceleration.
     */
    QuartInOut,

    /**
     * Ends slowly with a quartic deceleration.
     */
    QuartOut,

    /**
     * Starts slowly and accelerates quintically.
     */
    QuintIn,

    /**
     * Starts and ends slowly with a quintic acceleration.
     */
    QuintInOut,

    /**
     * Ends slowly with a quintic deceleration.
     */
    QuintOut,

    /**
     * Starts slowly and accelerates sinusoidally.
     */
    SineIn,

    /**
     * Starts and ends slowly with a sinusoidal acceleration.
     */
    SineInOut,

    /**
     * Ends slowly with a sinusoidal deceleration.
     */
    SineOut,
}
declare enum MessageBoxIcon {
    Info,

    Warning,

    Error,
}
declare enum MessageBoxResult {
    Yes,

    No,

    Ok,

    Cancel,
}
declare enum Method {
    Get,

    Post,

    Put,

    Delete,

    Head,

    Options,

    Connect,

    Patch,

    Trace,
}
declare interface Clipboard {
    setText(text: string, mode?: ClipboardMode): Promise<void>;
    getText(mode?: ClipboardMode): Promise<string>;
    setImage(image: Image, mode?: ClipboardMode): Promise<void>;
    getImage(mode?: ClipboardMode): Promise<Image>;
    getFileList(mode?: ClipboardMode): Promise<string[]>;
    setHtml(html: string, alt_text?: string, mode?: ClipboardMode): Promise<void>;
    getHtml(mode?: ClipboardMode): Promise<string>;
    clear(mode?: ClipboardMode): Promise<void>;
}
declare const clipboard: Clipboard;
declare class Image {
    /**
     * Creates a new empty image.
     * 
     * Example
     * ```js
     * let image = new Image(100, 100);
     * ```
     */
    constructor(width: number, height: number);
    static fromBytes(bytes: Uint8Array): Image;
    save(path: string): void;
    static load(path: string): Image;
    equals(other: Image): boolean;
    toString(): string;
    clone(): Image;
    /**
     * Invert the colors of this image.
     */
    invert(): this;
    /**
     * Invert the colors of this image and returns a new image.
     */
    inverted(): Image;
    /**
     * Blur the image.
     */
    blur(options?: BlurOptions): this;
    /**
     * Blur the image and returns a new image.
     */
    blurred(options?: BlurOptions): Image;
    /**
     * Rotate the image.
     */
    rotate(angle: number, options?: RotationOptions): this;
    /**
     * Rotate the image and returns a new image.
     */
    rotated(angle: number, options?: RotationOptions): Image;
    /**
     * Flip the image.
     */
    flip(flip_direction: FlipDirection): this;
    /**
     * Flip the image and returns a new image.
     */
    flipped(flip_direction: FlipDirection): Image;
    /**
     * Hue rotate the image.
     */
    hueRotate(value: number): this;
    /**
     * Hue rotate the image and returns a new image.
     */
    hueRotated(value: number): Image;
    /**
     * Transform this image into a grayscale.
     */
    grayscale(): this;
    /**
     * Returns a grayscale version of this image.
     */
    grayscaled(): Image;
    /**
     * Crops this image.
     */
    crop(rect: Rect): this;
    /**
     * Crops this image.
     */
    crop(x: number, y: number, width: number, height: number): this;
    /**
     * Crops this image.
     */
    crop(o: {x: number, y: number, width: number, height: number}): this;
    /**
     * Returns a cropped version of this image.
     */
    cropped(rect: Rect): Image;
    /**
     * Returns a cropped version of this image.
     */
    cropped(x: number, y: number, width: number, height: number): Image;
    /**
     * Returns a cropped version of this image.
     */
    cropped(o: {x: number, y: number, width: number, height: number}): Image;
    /**
     * Resizes this image.
     */
    resize(width: number, height: number, options?: ResizeOptions): this;
    /**
     * Returns a resized version of this image.
     */
    resized(width: number, height: number, options?: ResizeOptions): Image;
    /**
     * Brightens or darkens the pixels of this image.
     */
    adjustBrightness(value: number): this;
    /**
     * Returns a brightened or darkened version of this image.
     */
    adjustedBrightness(value: number): Image;
    /**
     * Adjusts the contrast of this image.
     */
    adjustContrast(value: number): this;
    /**
     * Returns a new image with an adjusted contrast.
     */
    adjustedContrast(value: number): Image;
    /**
     * Fill this image with a color.
     */
    fill(color: Color): this;
    /**
     * Fill this image with a color.
     */
    fill(r: number, g: number, b: number, a: number): this;
    /**
     * Fill this image with a color.
     */
    fill(r: number, g: number, b: number): this;
    /**
     * Fill this image with a color.
     */
    fill(o: {r: number, g: number, b: number}): this;
    /**
     * Fill this image with a color.
     */
    fill(o: {r: number, g: number, b: number, a: number}): this;
    /**
     * Fill this image with a color.
     */
    filled(color: Color): Image;
    /**
     * Fill this image with a color.
     */
    filled(r: number, g: number, b: number, a: number): Image;
    /**
     * Fill this image with a color.
     */
    filled(r: number, g: number, b: number): Image;
    /**
     * Fill this image with a color.
     */
    filled(o: {r: number, g: number, b: number}): Image;
    /**
     * Fill this image with a color.
     */
    filled(o: {r: number, g: number, b: number, a: number}): Image;
    /**
     * Returns the value of a pixel.
     */
    getPixel(position: Point): Color;
    /**
     * Returns the value of a pixel.
     */
    getPixel(x: number, y: number): Color;
    /**
     * Returns the value of a pixel.
     */
    getPixel(o: {x: number, y: number}): Color;
    /**
     * Returns the value of a pixel.
     */
    setPixel(position: Point, color: Color): this;
    /**
     * Returns the value of a pixel.
     */
    setPixel(position: Point, r: number, g: number, b: number, a: number): this;
    /**
     * Returns the value of a pixel.
     */
    setPixel(position: Point, r: number, g: number, b: number): this;
    /**
     * Returns the value of a pixel.
     */
    setPixel(position: Point, o: {r: number, g: number, b: number}): this;
    /**
     * Returns the value of a pixel.
     */
    setPixel(position: Point, o: {r: number, g: number, b: number, a: number}): this;
    /**
     * Returns the value of a pixel.
     */
    setPixel(x: number, y: number, color: Color): this;
    /**
     * Returns the value of a pixel.
     */
    setPixel(x: number, y: number, r: number, g: number, b: number, a: number): this;
    /**
     * Returns the value of a pixel.
     */
    setPixel(x: number, y: number, r: number, g: number, b: number): this;
    /**
     * Returns the value of a pixel.
     */
    setPixel(x: number, y: number, o: {r: number, g: number, b: number}): this;
    /**
     * Returns the value of a pixel.
     */
    setPixel(x: number, y: number, o: {r: number, g: number, b: number, a: number}): this;
    /**
     * Returns the value of a pixel.
     */
    setPixel(o: {x: number, y: number}, color: Color): this;
    /**
     * Returns the value of a pixel.
     */
    setPixel(o: {x: number, y: number}, r: number, g: number, b: number, a: number): this;
    /**
     * Returns the value of a pixel.
     */
    setPixel(o: {x: number, y: number}, r: number, g: number, b: number): this;
    /**
     * Returns the value of a pixel.
     */
    setPixel(o1: {x: number, y: number}, o2: {r: number, g: number, b: number}): this;
    /**
     * Returns the value of a pixel.
     */
    setPixel(o1: {x: number, y: number}, o2: {r: number, g: number, b: number, a: number}): this;
    /**
     * Creates a new image from a part of this image.
     */
    copyRegion(rect: Rect): Image;
    /**
     * Creates a new image from a part of this image.
     */
    copyRegion(x: number, y: number, width: number, height: number): Image;
    /**
     * Creates a new image from a part of this image.
     */
    copyRegion(o: {x: number, y: number, width: number, height: number}): Image;
    /**
     * Returns a Rect representing this image.
     */
    rect(): Rect;
    /**
     * Draw a cross on this image.
     */
    drawCross(position: Point, color: Color): this;
    /**
     * Draw a cross on this image.
     */
    drawCross(position: Point, r: number, g: number, b: number, a: number): this;
    /**
     * Draw a cross on this image.
     */
    drawCross(position: Point, r: number, g: number, b: number): this;
    /**
     * Draw a cross on this image.
     */
    drawCross(position: Point, o: {r: number, g: number, b: number}): this;
    /**
     * Draw a cross on this image.
     */
    drawCross(position: Point, o: {r: number, g: number, b: number, a: number}): this;
    /**
     * Draw a cross on this image.
     */
    drawCross(x: number, y: number, color: Color): this;
    /**
     * Draw a cross on this image.
     */
    drawCross(x: number, y: number, r: number, g: number, b: number, a: number): this;
    /**
     * Draw a cross on this image.
     */
    drawCross(x: number, y: number, r: number, g: number, b: number): this;
    /**
     * Draw a cross on this image.
     */
    drawCross(x: number, y: number, o: {r: number, g: number, b: number}): this;
    /**
     * Draw a cross on this image.
     */
    drawCross(x: number, y: number, o: {r: number, g: number, b: number, a: number}): this;
    /**
     * Draw a cross on this image.
     */
    drawCross(o: {x: number, y: number}, color: Color): this;
    /**
     * Draw a cross on this image.
     */
    drawCross(o: {x: number, y: number}, r: number, g: number, b: number, a: number): this;
    /**
     * Draw a cross on this image.
     */
    drawCross(o: {x: number, y: number}, r: number, g: number, b: number): this;
    /**
     * Draw a cross on this image.
     */
    drawCross(o1: {x: number, y: number}, o2: {r: number, g: number, b: number}): this;
    /**
     * Draw a cross on this image.
     */
    drawCross(o1: {x: number, y: number}, o2: {r: number, g: number, b: number, a: number}): this;
    /**
     * Draw a cross on a copy of this image.
     */
    withCross(position: Point, color: Color): Image;
    /**
     * Draw a cross on a copy of this image.
     */
    withCross(position: Point, r: number, g: number, b: number, a: number): Image;
    /**
     * Draw a cross on a copy of this image.
     */
    withCross(position: Point, r: number, g: number, b: number): Image;
    /**
     * Draw a cross on a copy of this image.
     */
    withCross(position: Point, o: {r: number, g: number, b: number}): Image;
    /**
     * Draw a cross on a copy of this image.
     */
    withCross(position: Point, o: {r: number, g: number, b: number, a: number}): Image;
    /**
     * Draw a cross on a copy of this image.
     */
    withCross(x: number, y: number, color: Color): Image;
    /**
     * Draw a cross on a copy of this image.
     */
    withCross(x: number, y: number, r: number, g: number, b: number, a: number): Image;
    /**
     * Draw a cross on a copy of this image.
     */
    withCross(x: number, y: number, r: number, g: number, b: number): Image;
    /**
     * Draw a cross on a copy of this image.
     */
    withCross(x: number, y: number, o: {r: number, g: number, b: number}): Image;
    /**
     * Draw a cross on a copy of this image.
     */
    withCross(x: number, y: number, o: {r: number, g: number, b: number, a: number}): Image;
    /**
     * Draw a cross on a copy of this image.
     */
    withCross(o: {x: number, y: number}, color: Color): Image;
    /**
     * Draw a cross on a copy of this image.
     */
    withCross(o: {x: number, y: number}, r: number, g: number, b: number, a: number): Image;
    /**
     * Draw a cross on a copy of this image.
     */
    withCross(o: {x: number, y: number}, r: number, g: number, b: number): Image;
    /**
     * Draw a cross on a copy of this image.
     */
    withCross(o1: {x: number, y: number}, o2: {r: number, g: number, b: number}): Image;
    /**
     * Draw a cross on a copy of this image.
     */
    withCross(o1: {x: number, y: number}, o2: {r: number, g: number, b: number, a: number}): Image;
    /**
     * Draw a line on this image.
     */
    drawLine(start: Point, end: Point, color: Color): this;
    /**
     * Draw a line on this image.
     */
    drawLine(start: Point, end: Point, r: number, g: number, b: number, a: number): this;
    /**
     * Draw a line on this image.
     */
    drawLine(start: Point, end: Point, r: number, g: number, b: number): this;
    /**
     * Draw a line on this image.
     */
    drawLine(start: Point, end: Point, o: {r: number, g: number, b: number}): this;
    /**
     * Draw a line on this image.
     */
    drawLine(start: Point, end: Point, o: {r: number, g: number, b: number, a: number}): this;
    /**
     * Draw a line on this image.
     */
    drawLine(start: Point, x: number, y: number, color: Color): this;
    /**
     * Draw a line on this image.
     */
    drawLine(start: Point, x: number, y: number, r: number, g: number, b: number, a: number): this;
    /**
     * Draw a line on this image.
     */
    drawLine(start: Point, x: number, y: number, r: number, g: number, b: number): this;
    /**
     * Draw a line on this image.
     */
    drawLine(start: Point, x: number, y: number, o: {r: number, g: number, b: number}): this;
    /**
     * Draw a line on this image.
     */
    drawLine(start: Point, x: number, y: number, o: {r: number, g: number, b: number, a: number}): this;
    /**
     * Draw a line on this image.
     */
    drawLine(start: Point, o: {x: number, y: number}, color: Color): this;
    /**
     * Draw a line on this image.
     */
    drawLine(start: Point, o: {x: number, y: number}, r: number, g: number, b: number, a: number): this;
    /**
     * Draw a line on this image.
     */
    drawLine(start: Point, o: {x: number, y: number}, r: number, g: number, b: number): this;
    /**
     * Draw a line on this image.
     */
    drawLine(start: Point, o1: {x: number, y: number}, o2: {r: number, g: number, b: number}): this;
    /**
     * Draw a line on this image.
     */
    drawLine(start: Point, o1: {x: number, y: number}, o2: {r: number, g: number, b: number, a: number}): this;
    /**
     * Draw a line on this image.
     */
    drawLine(x: number, y: number, end: Point, color: Color): this;
    /**
     * Draw a line on this image.
     */
    drawLine(x: number, y: number, end: Point, r: number, g: number, b: number, a: number): this;
    /**
     * Draw a line on this image.
     */
    drawLine(x: number, y: number, end: Point, r: number, g: number, b: number): this;
    /**
     * Draw a line on this image.
     */
    drawLine(x: number, y: number, end: Point, o: {r: number, g: number, b: number}): this;
    /**
     * Draw a line on this image.
     */
    drawLine(x: number, y: number, end: Point, o: {r: number, g: number, b: number, a: number}): this;
    /**
     * Draw a line on this image.
     */
    drawLine(x1: number, y1: number, x2: number, y2: number, color: Color): this;
    /**
     * Draw a line on this image.
     */
    drawLine(x1: number, y1: number, x2: number, y2: number, r: number, g: number, b: number, a: number): this;
    /**
     * Draw a line on this image.
     */
    drawLine(x1: number, y1: number, x2: number, y2: number, r: number, g: number, b: number): this;
    /**
     * Draw a line on this image.
     */
    drawLine(x1: number, y1: number, x2: number, y2: number, o: {r: number, g: number, b: number}): this;
    /**
     * Draw a line on this image.
     */
    drawLine(x1: number, y1: number, x2: number, y2: number, o: {r: number, g: number, b: number, a: number}): this;
    /**
     * Draw a line on this image.
     */
    drawLine(x: number, y: number, o: {x: number, y: number}, color: Color): this;
    /**
     * Draw a line on this image.
     */
    drawLine(x: number, y: number, o: {x: number, y: number}, r: number, g: number, b: number, a: number): this;
    /**
     * Draw a line on this image.
     */
    drawLine(x: number, y: number, o: {x: number, y: number}, r: number, g: number, b: number): this;
    /**
     * Draw a line on this image.
     */
    drawLine(x: number, y: number, o1: {x: number, y: number}, o2: {r: number, g: number, b: number}): this;
    /**
     * Draw a line on this image.
     */
    drawLine(x: number, y: number, o1: {x: number, y: number}, o2: {r: number, g: number, b: number, a: number}): this;
    /**
     * Draw a line on this image.
     */
    drawLine(o: {x: number, y: number}, end: Point, color: Color): this;
    /**
     * Draw a line on this image.
     */
    drawLine(o: {x: number, y: number}, end: Point, r: number, g: number, b: number, a: number): this;
    /**
     * Draw a line on this image.
     */
    drawLine(o: {x: number, y: number}, end: Point, r: number, g: number, b: number): this;
    /**
     * Draw a line on this image.
     */
    drawLine(o1: {x: number, y: number}, end: Point, o2: {r: number, g: number, b: number}): this;
    /**
     * Draw a line on this image.
     */
    drawLine(o1: {x: number, y: number}, end: Point, o2: {r: number, g: number, b: number, a: number}): this;
    /**
     * Draw a line on this image.
     */
    drawLine(o: {x: number, y: number}, x: number, y: number, color: Color): this;
    /**
     * Draw a line on this image.
     */
    drawLine(o: {x: number, y: number}, x: number, y: number, r: number, g: number, b: number, a: number): this;
    /**
     * Draw a line on this image.
     */
    drawLine(o: {x: number, y: number}, x: number, y: number, r: number, g: number, b: number): this;
    /**
     * Draw a line on this image.
     */
    drawLine(o1: {x: number, y: number}, x: number, y: number, o2: {r: number, g: number, b: number}): this;
    /**
     * Draw a line on this image.
     */
    drawLine(o1: {x: number, y: number}, x: number, y: number, o2: {r: number, g: number, b: number, a: number}): this;
    /**
     * Draw a line on this image.
     */
    drawLine(o1: {x: number, y: number}, o2: {x: number, y: number}, color: Color): this;
    /**
     * Draw a line on this image.
     */
    drawLine(o1: {x: number, y: number}, o2: {x: number, y: number}, r: number, g: number, b: number, a: number): this;
    /**
     * Draw a line on this image.
     */
    drawLine(o1: {x: number, y: number}, o2: {x: number, y: number}, r: number, g: number, b: number): this;
    /**
     * Draw a line on this image.
     */
    drawLine(o1: {x: number, y: number}, o2: {x: number, y: number}, o3: {r: number, g: number, b: number}): this;
    /**
     * Draw a line on this image.
     */
    drawLine(o1: {x: number, y: number}, o2: {x: number, y: number}, o3: {r: number, g: number, b: number, a: number}): this;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(start: Point, end: Point, color: Color): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(start: Point, end: Point, r: number, g: number, b: number, a: number): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(start: Point, end: Point, r: number, g: number, b: number): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(start: Point, end: Point, o: {r: number, g: number, b: number}): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(start: Point, end: Point, o: {r: number, g: number, b: number, a: number}): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(start: Point, x: number, y: number, color: Color): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(start: Point, x: number, y: number, r: number, g: number, b: number, a: number): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(start: Point, x: number, y: number, r: number, g: number, b: number): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(start: Point, x: number, y: number, o: {r: number, g: number, b: number}): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(start: Point, x: number, y: number, o: {r: number, g: number, b: number, a: number}): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(start: Point, o: {x: number, y: number}, color: Color): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(start: Point, o: {x: number, y: number}, r: number, g: number, b: number, a: number): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(start: Point, o: {x: number, y: number}, r: number, g: number, b: number): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(start: Point, o1: {x: number, y: number}, o2: {r: number, g: number, b: number}): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(start: Point, o1: {x: number, y: number}, o2: {r: number, g: number, b: number, a: number}): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(x: number, y: number, end: Point, color: Color): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(x: number, y: number, end: Point, r: number, g: number, b: number, a: number): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(x: number, y: number, end: Point, r: number, g: number, b: number): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(x: number, y: number, end: Point, o: {r: number, g: number, b: number}): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(x: number, y: number, end: Point, o: {r: number, g: number, b: number, a: number}): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(x1: number, y1: number, x2: number, y2: number, color: Color): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(x1: number, y1: number, x2: number, y2: number, r: number, g: number, b: number, a: number): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(x1: number, y1: number, x2: number, y2: number, r: number, g: number, b: number): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(x1: number, y1: number, x2: number, y2: number, o: {r: number, g: number, b: number}): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(x1: number, y1: number, x2: number, y2: number, o: {r: number, g: number, b: number, a: number}): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(x: number, y: number, o: {x: number, y: number}, color: Color): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(x: number, y: number, o: {x: number, y: number}, r: number, g: number, b: number, a: number): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(x: number, y: number, o: {x: number, y: number}, r: number, g: number, b: number): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(x: number, y: number, o1: {x: number, y: number}, o2: {r: number, g: number, b: number}): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(x: number, y: number, o1: {x: number, y: number}, o2: {r: number, g: number, b: number, a: number}): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(o: {x: number, y: number}, end: Point, color: Color): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(o: {x: number, y: number}, end: Point, r: number, g: number, b: number, a: number): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(o: {x: number, y: number}, end: Point, r: number, g: number, b: number): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(o1: {x: number, y: number}, end: Point, o2: {r: number, g: number, b: number}): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(o1: {x: number, y: number}, end: Point, o2: {r: number, g: number, b: number, a: number}): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(o: {x: number, y: number}, x: number, y: number, color: Color): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(o: {x: number, y: number}, x: number, y: number, r: number, g: number, b: number, a: number): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(o: {x: number, y: number}, x: number, y: number, r: number, g: number, b: number): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(o1: {x: number, y: number}, x: number, y: number, o2: {r: number, g: number, b: number}): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(o1: {x: number, y: number}, x: number, y: number, o2: {r: number, g: number, b: number, a: number}): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(o1: {x: number, y: number}, o2: {x: number, y: number}, color: Color): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(o1: {x: number, y: number}, o2: {x: number, y: number}, r: number, g: number, b: number, a: number): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(o1: {x: number, y: number}, o2: {x: number, y: number}, r: number, g: number, b: number): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(o1: {x: number, y: number}, o2: {x: number, y: number}, o3: {r: number, g: number, b: number}): Image;
    /**
     * Draw a line on a copy of this image.
     */
    withLine(o1: {x: number, y: number}, o2: {x: number, y: number}, o3: {r: number, g: number, b: number, a: number}): Image;
    /**
     * Draw a circle on this image.
     */
    drawCircle(center: Point, radius: number, color: Color, options?: DrawingOptions): this;
    /**
     * Draw a circle on this image.
     */
    drawCircle(center: Point, radius: number, r: number, g: number, b: number, a: number, options?: DrawingOptions): this;
    /**
     * Draw a circle on this image.
     */
    drawCircle(center: Point, radius: number, r: number, g: number, b: number, options?: DrawingOptions): this;
    /**
     * Draw a circle on this image.
     */
    drawCircle(center: Point, radius: number, o: {r: number, g: number, b: number}, options?: DrawingOptions): this;
    /**
     * Draw a circle on this image.
     */
    drawCircle(center: Point, radius: number, o: {r: number, g: number, b: number, a: number}, options?: DrawingOptions): this;
    /**
     * Draw a circle on this image.
     */
    drawCircle(x: number, y: number, radius: number, color: Color, options?: DrawingOptions): this;
    /**
     * Draw a circle on this image.
     */
    drawCircle(x: number, y: number, radius: number, r: number, g: number, b: number, a: number, options?: DrawingOptions): this;
    /**
     * Draw a circle on this image.
     */
    drawCircle(x: number, y: number, radius: number, r: number, g: number, b: number, options?: DrawingOptions): this;
    /**
     * Draw a circle on this image.
     */
    drawCircle(x: number, y: number, radius: number, o: {r: number, g: number, b: number}, options?: DrawingOptions): this;
    /**
     * Draw a circle on this image.
     */
    drawCircle(x: number, y: number, radius: number, o: {r: number, g: number, b: number, a: number}, options?: DrawingOptions): this;
    /**
     * Draw a circle on this image.
     */
    drawCircle(o: {x: number, y: number}, radius: number, color: Color, options?: DrawingOptions): this;
    /**
     * Draw a circle on this image.
     */
    drawCircle(o: {x: number, y: number}, radius: number, r: number, g: number, b: number, a: number, options?: DrawingOptions): this;
    /**
     * Draw a circle on this image.
     */
    drawCircle(o: {x: number, y: number}, radius: number, r: number, g: number, b: number, options?: DrawingOptions): this;
    /**
     * Draw a circle on this image.
     */
    drawCircle(o1: {x: number, y: number}, radius: number, o2: {r: number, g: number, b: number}, options?: DrawingOptions): this;
    /**
     * Draw a circle on this image.
     */
    drawCircle(o1: {x: number, y: number}, radius: number, o2: {r: number, g: number, b: number, a: number}, options?: DrawingOptions): this;
    /**
     * Draw a circle on a copy of this image.
     */
    withCircle(center: Point, radius: number, color: Color, options?: DrawingOptions): Image;
    /**
     * Draw a circle on a copy of this image.
     */
    withCircle(center: Point, radius: number, r: number, g: number, b: number, a: number, options?: DrawingOptions): Image;
    /**
     * Draw a circle on a copy of this image.
     */
    withCircle(center: Point, radius: number, r: number, g: number, b: number, options?: DrawingOptions): Image;
    /**
     * Draw a circle on a copy of this image.
     */
    withCircle(center: Point, radius: number, o: {r: number, g: number, b: number}, options?: DrawingOptions): Image;
    /**
     * Draw a circle on a copy of this image.
     */
    withCircle(center: Point, radius: number, o: {r: number, g: number, b: number, a: number}, options?: DrawingOptions): Image;
    /**
     * Draw a circle on a copy of this image.
     */
    withCircle(x: number, y: number, radius: number, color: Color, options?: DrawingOptions): Image;
    /**
     * Draw a circle on a copy of this image.
     */
    withCircle(x: number, y: number, radius: number, r: number, g: number, b: number, a: number, options?: DrawingOptions): Image;
    /**
     * Draw a circle on a copy of this image.
     */
    withCircle(x: number, y: number, radius: number, r: number, g: number, b: number, options?: DrawingOptions): Image;
    /**
     * Draw a circle on a copy of this image.
     */
    withCircle(x: number, y: number, radius: number, o: {r: number, g: number, b: number}, options?: DrawingOptions): Image;
    /**
     * Draw a circle on a copy of this image.
     */
    withCircle(x: number, y: number, radius: number, o: {r: number, g: number, b: number, a: number}, options?: DrawingOptions): Image;
    /**
     * Draw a circle on a copy of this image.
     */
    withCircle(o: {x: number, y: number}, radius: number, color: Color, options?: DrawingOptions): Image;
    /**
     * Draw a circle on a copy of this image.
     */
    withCircle(o: {x: number, y: number}, radius: number, r: number, g: number, b: number, a: number, options?: DrawingOptions): Image;
    /**
     * Draw a circle on a copy of this image.
     */
    withCircle(o: {x: number, y: number}, radius: number, r: number, g: number, b: number, options?: DrawingOptions): Image;
    /**
     * Draw a circle on a copy of this image.
     */
    withCircle(o1: {x: number, y: number}, radius: number, o2: {r: number, g: number, b: number}, options?: DrawingOptions): Image;
    /**
     * Draw a circle on a copy of this image.
     */
    withCircle(o1: {x: number, y: number}, radius: number, o2: {r: number, g: number, b: number, a: number}, options?: DrawingOptions): Image;
    /**
     * Draw an ellipse on this image.
     */
    drawEllipse(center: Point, width_radius: number, height_radius: number, color: Color, options?: DrawingOptions): this;
    /**
     * Draw an ellipse on this image.
     */
    drawEllipse(center: Point, width_radius: number, height_radius: number, r: number, g: number, b: number, a: number, options?: DrawingOptions): this;
    /**
     * Draw an ellipse on this image.
     */
    drawEllipse(center: Point, width_radius: number, height_radius: number, r: number, g: number, b: number, options?: DrawingOptions): this;
    /**
     * Draw an ellipse on this image.
     */
    drawEllipse(center: Point, width_radius: number, height_radius: number, o: {r: number, g: number, b: number}, options?: DrawingOptions): this;
    /**
     * Draw an ellipse on this image.
     */
    drawEllipse(center: Point, width_radius: number, height_radius: number, o: {r: number, g: number, b: number, a: number}, options?: DrawingOptions): this;
    /**
     * Draw an ellipse on this image.
     */
    drawEllipse(x: number, y: number, width_radius: number, height_radius: number, color: Color, options?: DrawingOptions): this;
    /**
     * Draw an ellipse on this image.
     */
    drawEllipse(x: number, y: number, width_radius: number, height_radius: number, r: number, g: number, b: number, a: number, options?: DrawingOptions): this;
    /**
     * Draw an ellipse on this image.
     */
    drawEllipse(x: number, y: number, width_radius: number, height_radius: number, r: number, g: number, b: number, options?: DrawingOptions): this;
    /**
     * Draw an ellipse on this image.
     */
    drawEllipse(x: number, y: number, width_radius: number, height_radius: number, o: {r: number, g: number, b: number}, options?: DrawingOptions): this;
    /**
     * Draw an ellipse on this image.
     */
    drawEllipse(x: number, y: number, width_radius: number, height_radius: number, o: {r: number, g: number, b: number, a: number}, options?: DrawingOptions): this;
    /**
     * Draw an ellipse on this image.
     */
    drawEllipse(o: {x: number, y: number}, width_radius: number, height_radius: number, color: Color, options?: DrawingOptions): this;
    /**
     * Draw an ellipse on this image.
     */
    drawEllipse(o: {x: number, y: number}, width_radius: number, height_radius: number, r: number, g: number, b: number, a: number, options?: DrawingOptions): this;
    /**
     * Draw an ellipse on this image.
     */
    drawEllipse(o: {x: number, y: number}, width_radius: number, height_radius: number, r: number, g: number, b: number, options?: DrawingOptions): this;
    /**
     * Draw an ellipse on this image.
     */
    drawEllipse(o1: {x: number, y: number}, width_radius: number, height_radius: number, o2: {r: number, g: number, b: number}, options?: DrawingOptions): this;
    /**
     * Draw an ellipse on this image.
     */
    drawEllipse(o1: {x: number, y: number}, width_radius: number, height_radius: number, o2: {r: number, g: number, b: number, a: number}, options?: DrawingOptions): this;
    /**
     * Draw an ellipse on a copy of this image.
     */
    withEllipse(center: Point, width_radius: number, height_radius: number, color: Color, options?: DrawingOptions): Image;
    /**
     * Draw an ellipse on a copy of this image.
     */
    withEllipse(center: Point, width_radius: number, height_radius: number, r: number, g: number, b: number, a: number, options?: DrawingOptions): Image;
    /**
     * Draw an ellipse on a copy of this image.
     */
    withEllipse(center: Point, width_radius: number, height_radius: number, r: number, g: number, b: number, options?: DrawingOptions): Image;
    /**
     * Draw an ellipse on a copy of this image.
     */
    withEllipse(center: Point, width_radius: number, height_radius: number, o: {r: number, g: number, b: number}, options?: DrawingOptions): Image;
    /**
     * Draw an ellipse on a copy of this image.
     */
    withEllipse(center: Point, width_radius: number, height_radius: number, o: {r: number, g: number, b: number, a: number}, options?: DrawingOptions): Image;
    /**
     * Draw an ellipse on a copy of this image.
     */
    withEllipse(x: number, y: number, width_radius: number, height_radius: number, color: Color, options?: DrawingOptions): Image;
    /**
     * Draw an ellipse on a copy of this image.
     */
    withEllipse(x: number, y: number, width_radius: number, height_radius: number, r: number, g: number, b: number, a: number, options?: DrawingOptions): Image;
    /**
     * Draw an ellipse on a copy of this image.
     */
    withEllipse(x: number, y: number, width_radius: number, height_radius: number, r: number, g: number, b: number, options?: DrawingOptions): Image;
    /**
     * Draw an ellipse on a copy of this image.
     */
    withEllipse(x: number, y: number, width_radius: number, height_radius: number, o: {r: number, g: number, b: number}, options?: DrawingOptions): Image;
    /**
     * Draw an ellipse on a copy of this image.
     */
    withEllipse(x: number, y: number, width_radius: number, height_radius: number, o: {r: number, g: number, b: number, a: number}, options?: DrawingOptions): Image;
    /**
     * Draw an ellipse on a copy of this image.
     */
    withEllipse(o: {x: number, y: number}, width_radius: number, height_radius: number, color: Color, options?: DrawingOptions): Image;
    /**
     * Draw an ellipse on a copy of this image.
     */
    withEllipse(o: {x: number, y: number}, width_radius: number, height_radius: number, r: number, g: number, b: number, a: number, options?: DrawingOptions): Image;
    /**
     * Draw an ellipse on a copy of this image.
     */
    withEllipse(o: {x: number, y: number}, width_radius: number, height_radius: number, r: number, g: number, b: number, options?: DrawingOptions): Image;
    /**
     * Draw an ellipse on a copy of this image.
     */
    withEllipse(o1: {x: number, y: number}, width_radius: number, height_radius: number, o2: {r: number, g: number, b: number}, options?: DrawingOptions): Image;
    /**
     * Draw an ellipse on a copy of this image.
     */
    withEllipse(o1: {x: number, y: number}, width_radius: number, height_radius: number, o2: {r: number, g: number, b: number, a: number}, options?: DrawingOptions): Image;
    /**
     * Draw a rectangle on this image.
     */
    drawRectangle(rect: Rect, color: Color, options?: DrawingOptions): this;
    /**
     * Draw a rectangle on this image.
     */
    drawRectangle(rect: Rect, r: number, g: number, b: number, a: number, options?: DrawingOptions): this;
    /**
     * Draw a rectangle on this image.
     */
    drawRectangle(rect: Rect, r: number, g: number, b: number, options?: DrawingOptions): this;
    /**
     * Draw a rectangle on this image.
     */
    drawRectangle(rect: Rect, o: {r: number, g: number, b: number}, options?: DrawingOptions): this;
    /**
     * Draw a rectangle on this image.
     */
    drawRectangle(rect: Rect, o: {r: number, g: number, b: number, a: number}, options?: DrawingOptions): this;
    /**
     * Draw a rectangle on this image.
     */
    drawRectangle(x: number, y: number, width: number, height: number, color: Color, options?: DrawingOptions): this;
    /**
     * Draw a rectangle on this image.
     */
    drawRectangle(x: number, y: number, width: number, height: number, r: number, g: number, b: number, a: number, options?: DrawingOptions): this;
    /**
     * Draw a rectangle on this image.
     */
    drawRectangle(x: number, y: number, width: number, height: number, r: number, g: number, b: number, options?: DrawingOptions): this;
    /**
     * Draw a rectangle on this image.
     */
    drawRectangle(x: number, y: number, width: number, height: number, o: {r: number, g: number, b: number}, options?: DrawingOptions): this;
    /**
     * Draw a rectangle on this image.
     */
    drawRectangle(x: number, y: number, width: number, height: number, o: {r: number, g: number, b: number, a: number}, options?: DrawingOptions): this;
    /**
     * Draw a rectangle on this image.
     */
    drawRectangle(o: {x: number, y: number, width: number, height: number}, color: Color, options?: DrawingOptions): this;
    /**
     * Draw a rectangle on this image.
     */
    drawRectangle(o: {x: number, y: number, width: number, height: number}, r: number, g: number, b: number, a: number, options?: DrawingOptions): this;
    /**
     * Draw a rectangle on this image.
     */
    drawRectangle(o: {x: number, y: number, width: number, height: number}, r: number, g: number, b: number, options?: DrawingOptions): this;
    /**
     * Draw a rectangle on this image.
     */
    drawRectangle(o1: {x: number, y: number, width: number, height: number}, o2: {r: number, g: number, b: number}, options?: DrawingOptions): this;
    /**
     * Draw a rectangle on this image.
     */
    drawRectangle(o1: {x: number, y: number, width: number, height: number}, o2: {r: number, g: number, b: number, a: number}, options?: DrawingOptions): this;
    /**
     * Draw a rectangle on a copy of this image.
     */
    withRectangle(rect: Rect, color: Color, options?: DrawingOptions): Image;
    /**
     * Draw a rectangle on a copy of this image.
     */
    withRectangle(rect: Rect, r: number, g: number, b: number, a: number, options?: DrawingOptions): Image;
    /**
     * Draw a rectangle on a copy of this image.
     */
    withRectangle(rect: Rect, r: number, g: number, b: number, options?: DrawingOptions): Image;
    /**
     * Draw a rectangle on a copy of this image.
     */
    withRectangle(rect: Rect, o: {r: number, g: number, b: number}, options?: DrawingOptions): Image;
    /**
     * Draw a rectangle on a copy of this image.
     */
    withRectangle(rect: Rect, o: {r: number, g: number, b: number, a: number}, options?: DrawingOptions): Image;
    /**
     * Draw a rectangle on a copy of this image.
     */
    withRectangle(x: number, y: number, width: number, height: number, color: Color, options?: DrawingOptions): Image;
    /**
     * Draw a rectangle on a copy of this image.
     */
    withRectangle(x: number, y: number, width: number, height: number, r: number, g: number, b: number, a: number, options?: DrawingOptions): Image;
    /**
     * Draw a rectangle on a copy of this image.
     */
    withRectangle(x: number, y: number, width: number, height: number, r: number, g: number, b: number, options?: DrawingOptions): Image;
    /**
     * Draw a rectangle on a copy of this image.
     */
    withRectangle(x: number, y: number, width: number, height: number, o: {r: number, g: number, b: number}, options?: DrawingOptions): Image;
    /**
     * Draw a rectangle on a copy of this image.
     */
    withRectangle(x: number, y: number, width: number, height: number, o: {r: number, g: number, b: number, a: number}, options?: DrawingOptions): Image;
    /**
     * Draw a rectangle on a copy of this image.
     */
    withRectangle(o: {x: number, y: number, width: number, height: number}, color: Color, options?: DrawingOptions): Image;
    /**
     * Draw a rectangle on a copy of this image.
     */
    withRectangle(o: {x: number, y: number, width: number, height: number}, r: number, g: number, b: number, a: number, options?: DrawingOptions): Image;
    /**
     * Draw a rectangle on a copy of this image.
     */
    withRectangle(o: {x: number, y: number, width: number, height: number}, r: number, g: number, b: number, options?: DrawingOptions): Image;
    /**
     * Draw a rectangle on a copy of this image.
     */
    withRectangle(o1: {x: number, y: number, width: number, height: number}, o2: {r: number, g: number, b: number}, options?: DrawingOptions): Image;
    /**
     * Draw a rectangle on a copy of this image.
     */
    withRectangle(o1: {x: number, y: number, width: number, height: number}, o2: {r: number, g: number, b: number, a: number}, options?: DrawingOptions): Image;
    /**
     * Draw another image on this image.
     */
    drawImage(position: Point, image: Image, options?: DrawImageOptions): this;
    /**
     * Draw another image on this image.
     */
    drawImage(x: number, y: number, image: Image, options?: DrawImageOptions): this;
    /**
     * Draw another image on this image.
     */
    drawImage(o: {x: number, y: number}, image: Image, options?: DrawImageOptions): this;
    /**
     * Draw another image on a copy of this image.
     */
    withImage(position: Point, image: Image, options?: DrawImageOptions): Image;
    /**
     * Draw another image on a copy of this image.
     */
    withImage(x: number, y: number, image: Image, options?: DrawImageOptions): Image;
    /**
     * Draw another image on a copy of this image.
     */
    withImage(o: {x: number, y: number}, image: Image, options?: DrawImageOptions): Image;
    /**
     * TODO
     */
    findImage(_image: Image, options?: FindImageOptions): void;
    width(): number;
    height(): number;
}
/**
 * A Color.
 * 
 * 
 * 
 * 
 * ```js
 * let c = new Color(128, 255, 255, 255);
 * ```
 */
declare class Color {
    static readonly Red: Color;
    static readonly Green: Color;
    static readonly Blue: Color;
    static readonly White: Color;
    static readonly Black: Color;
    static readonly Transparent: Color;
    static readonly AliceBlue: Color;
    static readonly AntiqueWhite: Color;
    static readonly Aqua: Color;
    static readonly Aquamarine: Color;
    static readonly Azure: Color;
    static readonly Beige: Color;
    static readonly Bisque: Color;
    static readonly BlanchedAlmond: Color;
    static readonly BlueViolet: Color;
    static readonly Brown: Color;
    static readonly BurlyWood: Color;
    static readonly CadetBlue: Color;
    static readonly Chartreuse: Color;
    static readonly Chocolate: Color;
    static readonly Coral: Color;
    static readonly CornflowerBlue: Color;
    static readonly Cornsilk: Color;
    static readonly Crimson: Color;
    static readonly Cyan: Color;
    static readonly DarkBlue: Color;
    static readonly DarkCyan: Color;
    static readonly DarkGoldenRod: Color;
    static readonly DarkGray: Color;
    static readonly DarkGreen: Color;
    static readonly DarkKhaki: Color;
    static readonly DarkMagenta: Color;
    static readonly DarkOliveGreen: Color;
    static readonly DarkOrange: Color;
    static readonly DarkOrchid: Color;
    static readonly DarkRed: Color;
    static readonly DarkSalmon: Color;
    static readonly DarkSeaGreen: Color;
    static readonly DarkSlateBlue: Color;
    static readonly DarkSlateGray: Color;
    static readonly DarkTurquoise: Color;
    static readonly DarkViolet: Color;
    static readonly DeepPink: Color;
    static readonly DeepSkyBlue: Color;
    static readonly DimGray: Color;
    static readonly DodgerBlue: Color;
    static readonly Firebrick: Color;
    static readonly FloralWhite: Color;
    static readonly ForestGreen: Color;
    static readonly Fuchsia: Color;
    static readonly Gainsboro: Color;
    static readonly GhostWhite: Color;
    static readonly Gold: Color;
    static readonly GoldenRod: Color;
    static readonly Gray: Color;
    static readonly GreenYellow: Color;
    static readonly HoneyDew: Color;
    static readonly HotPink: Color;
    static readonly IndianRed: Color;
    static readonly Indigo: Color;
    static readonly Ivory: Color;
    static readonly Khaki: Color;
    static readonly Lavender: Color;
    static readonly LavenderBlush: Color;
    static readonly LawnGreen: Color;
    static readonly LemonChiffon: Color;
    static readonly LightBlue: Color;
    static readonly LightCoral: Color;
    static readonly LightCyan: Color;
    static readonly LightGoldenRodYellow: Color;
    static readonly LightGray: Color;
    static readonly LightGreen: Color;
    static readonly LightPink: Color;
    static readonly LightSalmon: Color;
    static readonly LightSeaGreen: Color;
    static readonly LightSkyBlue: Color;
    static readonly LightSlateGray: Color;
    static readonly LightSteelBlue: Color;
    static readonly LightYellow: Color;
    static readonly Lime: Color;
    static readonly LimeGreen: Color;
    static readonly Linen: Color;
    static readonly Magenta: Color;
    static readonly Maroon: Color;
    static readonly MediumAquaMarine: Color;
    static readonly MediumBlue: Color;
    static readonly MediumOrchid: Color;
    static readonly MediumPurple: Color;
    static readonly MediumSeaGreen: Color;
    static readonly MediumSlateBlue: Color;
    static readonly MediumSpringGreen: Color;
    static readonly MediumTurquoise: Color;
    static readonly MediumVioletRed: Color;
    static readonly MidnightBlue: Color;
    static readonly MintCream: Color;
    static readonly MistyRose: Color;
    static readonly Moccasin: Color;
    static readonly NavajoWhite: Color;
    static readonly Navy: Color;
    static readonly OldLace: Color;
    static readonly Olive: Color;
    static readonly OliveDrab: Color;
    static readonly Orange: Color;
    static readonly OrangeRed: Color;
    static readonly Orchid: Color;
    static readonly PaleGoldenRod: Color;
    static readonly PaleGreen: Color;
    static readonly PaleTurquoise: Color;
    static readonly PaleVioletRed: Color;
    static readonly PapayaWhip: Color;
    static readonly PeachPuff: Color;
    static readonly Peru: Color;
    static readonly Pink: Color;
    static readonly Plum: Color;
    static readonly PowderBlue: Color;
    static readonly Purple: Color;
    static readonly RebeccaPurple: Color;
    static readonly RosyBrown: Color;
    static readonly RoyalBlue: Color;
    static readonly SaddleBrown: Color;
    static readonly Salmon: Color;
    static readonly SandyBrown: Color;
    static readonly SeaGreen: Color;
    static readonly SeaShell: Color;
    static readonly Sienna: Color;
    static readonly Silver: Color;
    static readonly SkyBlue: Color;
    static readonly SlateBlue: Color;
    static readonly SlateGray: Color;
    static readonly Snow: Color;
    static readonly SpringGreen: Color;
    static readonly SteelBlue: Color;
    static readonly Tan: Color;
    static readonly Teal: Color;
    static readonly Thistle: Color;
    static readonly Tomato: Color;
    static readonly Turquoise: Color;
    static readonly Violet: Color;
    static readonly Wheat: Color;
    static readonly WhiteSmoke: Color;
    static readonly Yellow: Color;
    static readonly YellowGreen: Color;
    /**
     * Red (should be between 0-255)
     */
    r: number;
    /**
     * Green (should be between 0-255)
     */
    g: number;
    /**
     * Blue (should be between 0-255)
     */
    b: number;
    /**
     * Alpha (should be between 0-255)
     */
    a: number;
    /**
     * Constructor with three color channels and an alpha channel.
     */
    constructor(r: number, g: number, b: number, a: number);
    /**
     * Constructor with three color channels.
     */
    constructor(r: number, g: number, b: number);
    /**
     * Constructor with an object.
     */
    constructor(o: {r: number, g: number, b: number});
    /**
     * Constructor with an object.
     */
    constructor(o: {r: number, g: number, b: number, a: number});
    /**
     * Constructor with another Color.
     */
    constructor(c: Color);
    equals(other: Color): boolean;
    equals(r: number, g: number, b: number, a: number): boolean;
    equals(r: number, g: number, b: number): boolean;
    equals(o: {r: number, g: number, b: number}): boolean;
    equals(o: {r: number, g: number, b: number, a: number}): boolean;
    toString(): string;
    clone(): Color;
}
declare interface Console {
    print(...args: any[]): void;
    printLn(...args: any[]): void;
    log(...args: any[]): void;
    info(...args: any[]): void;
    warn(...args: any[]): void;
    error(...args: any[]): void;
    clear(): void;
    time(name?: string): void;
    timeEnd(name?: string): void;
    count(name?: string): void;
}
declare const console: Console;
/**
 * Directory entry
 */
declare interface DirectoryEntry {
    readonly path: string;
    readonly fileName: string;
    readonly isFile: boolean;
    readonly isDirectory: boolean;
    readonly isSymlink: boolean;
    readonly size: number;
}
/**
 * Directory options
 */
declare interface DirectoryOptions {
    /**
     * Should the directories be created or removed recursively?
     * @defaultValue true
     */
    recursive?: boolean;
}
/**
 * Directory list options
 */
declare interface DirectoryListOptions {
    /**
     * Should the entries be sorted?
     * @defaultValue true
     */
    sort?: boolean;
    /**
     * Should each entry's absolute path be computed?
     * @defaultValue true
     */
    absolutePath?: boolean;
    /**
     * Should each entry's size be fetched?
     * @defaultValue true
     */
    fetchSize?: boolean;
}
declare class Directory {
    private constructor();
    static create(path: string, options?: DirectoryOptions): Promise<void>;
    static remove(path: string, options?: DirectoryOptions): Promise<void>;
    static listEntries(path: string, options?: DirectoryListOptions): Promise<DirectoryEntry[]>;
}
declare interface Displays {
    randomPoint(): Point;
    fromPoint(point: Point): DisplayInfo | undefined;
    fromPoint(x: number, y: number): DisplayInfo | undefined;
    fromPoint(o: {x: number, y: number}): DisplayInfo | undefined;
    fromName(name: Name): DisplayInfo | undefined;
    fromName(name: string): DisplayInfo | undefined;
    fromName(wildcard: Wildcard): DisplayInfo | undefined;
    fromName(regexp: RegExp): DisplayInfo | undefined;
    fromDeviceName(name: Name): DisplayInfo | undefined;
    fromDeviceName(name: string): DisplayInfo | undefined;
    fromDeviceName(wildcard: Wildcard): DisplayInfo | undefined;
    fromDeviceName(regexp: RegExp): DisplayInfo | undefined;
    fromId(id: number): DisplayInfo | undefined;
    smallest(): DisplayInfo | undefined;
    largest(): DisplayInfo | undefined;
}
declare const displays: Displays;
/**
 * A 2D Point.
 * 
 * 
 * ```js
 * let p = new Point(1, 2);
 * ```
 */
declare class Point {
    /**
     * X coordinate
     */
    x: number;
    /**
     * Y coordinate
     */
    y: number;
    /**
     * Constructor with two numbers.
     */
    constructor(x: number, y: number);
    /**
     * Constructor with an object.
     */
    constructor(o: {x: number, y: number});
    /**
     * Constructor with another Point.
     */
    constructor(p: Point);
    /**
     * Length of this point.
     */
    length(): number;
    /**
     * Returns a random point around this point.
     */
    static randomInCircle(center: Point, radius: number): Point;
    /**
     * Returns a random point around this point.
     */
    static randomInCircle(x: number, y: number, radius: number): Point;
    /**
     * Returns a random point around this point.
     */
    static randomInCircle(o: {x: number, y: number}, radius: number): Point;
    /**
     * Calculates the distance between this point and another.
     */
    distanceTo(other: Point): number;
    /**
     * Calculates the distance between this point and another.
     */
    distanceTo(x: number, y: number): number;
    /**
     * Calculates the distance between this point and another.
     */
    distanceTo(o: {x: number, y: number}): number;
    /**
     * Returns a JSON representation of this Point.
     */
    toJson(): string;
    /**
     * Returns true if this Point is at the origin, (0, 0).
     */
    isOrigin(): boolean;
    /**
     * Computes the distance between two points.
     */
    static distance(a: Point, b: Point): number;
    /**
     * Computes the distance between two points.
     */
    static distance(a: Point, x: number, y: number): number;
    /**
     * Computes the distance between two points.
     */
    static distance(a: Point, o: {x: number, y: number}): number;
    /**
     * Computes the distance between two points.
     */
    static distance(x: number, y: number, b: Point): number;
    /**
     * Computes the distance between two points.
     */
    static distance(x1: number, y1: number, x2: number, y2: number): number;
    /**
     * Computes the distance between two points.
     */
    static distance(x: number, y: number, o: {x: number, y: number}): number;
    /**
     * Computes the distance between two points.
     */
    static distance(o: {x: number, y: number}, b: Point): number;
    /**
     * Computes the distance between two points.
     */
    static distance(o: {x: number, y: number}, x: number, y: number): number;
    /**
     * Computes the distance between two points.
     */
    static distance(o1: {x: number, y: number}, o2: {x: number, y: number}): number;
    /**
     * Returns true if a Point equals another.
     */
    equals(other: Point): boolean;
    /**
     * Returns true if a Point equals another.
     */
    equals(x: number, y: number): boolean;
    /**
     * Returns true if a Point equals another.
     */
    equals(o: {x: number, y: number}): boolean;
    /**
     * Adds two points and returns a new Point.
     */
    add(other: Point): Point;
    /**
     * Adds two points and returns a new Point.
     */
    add(x: number, y: number): Point;
    /**
     * Adds two points and returns a new Point.
     */
    add(o: {x: number, y: number}): Point;
    /**
     * Subtracts two points and returns a new Point.
     */
    subtract(other: Point): Point;
    /**
     * Subtracts two points and returns a new Point.
     */
    subtract(x: number, y: number): Point;
    /**
     * Subtracts two points and returns a new Point.
     */
    subtract(o: {x: number, y: number}): Point;
    /**
     * Scales this point by a factor and returns a new Point.
     */
    scaled(factor: number): Point;
    /**
     * Returns a string representation of this Point.
     */
    toString(): string;
    /**
     * Clones this Point.
     */
    clone(): Point;
}
/**
 * Display info
 */
declare interface DisplayInfo {
    /**
     * Unique identifier associated with the display
     */
    readonly id: number;
    /**
     * The display name
     */
    readonly name: string;
    /**
     * The display friendly name
     */
    readonly friendlyName: string;
    /**
     * The display x coordinate
     */
    readonly x: number;
    /**
     * The display x coordinate
     */
    readonly y: number;
    /**
     * The display pixel width
     */
    readonly width: number;
    /**
     * The display pixel height
     */
    readonly height: number;
    /**
     * The width of a display in millimeters. This value may be 0
     */
    readonly widthMm: number;
    /**
     * The height of a display in millimeters. This value may be 0
     */
    readonly heightMm: number;
    /**
     * Can be 0, 90, 180, 270, represents screen rotation in clock-wise degrees
     */
    readonly rotation: number;
    /**
     * Output device's pixel scale factor
     */
    readonly scaleFactor: number;
    /**
     * The display refresh rate
     */
    readonly frequency: number;
    /**
     * Whether the screen is the main screen
     */
    readonly isPrimary: boolean;
}
declare class Rect {
    /**
     * Constructor with a position and a size.
     */
    constructor(x: number, y: number, width: number, height: number);
    /**
     * Constructor with an object.
     */
    constructor(o: {x: number, y: number, width: number, height: number});
    /**
     * Constructor with another Rect.
     */
    constructor(r: Rect);
    equals(other: Rect): boolean;
    equals(x: number, y: number, width: number, height: number): boolean;
    equals(o: {x: number, y: number, width: number, height: number}): boolean;
    contains(point: Point): boolean;
    contains(x: number, y: number): boolean;
    contains(o: {x: number, y: number}): boolean;
    toString(): string;
    clone(): Rect;
    intersects(other: Rect): boolean;
    intersects(x: number, y: number, width: number, height: number): boolean;
    intersects(o: {x: number, y: number, width: number, height: number}): boolean;
    intersection(other: Rect): Rect | undefined;
    intersection(x: number, y: number, width: number, height: number): Rect | undefined;
    intersection(o: {x: number, y: number, width: number, height: number}): Rect | undefined;
    union(other: Rect): Rect;
    union(x: number, y: number, width: number, height: number): Rect;
    union(o: {x: number, y: number, width: number, height: number}): Rect;
}
/**
 * File open options
 */
declare interface OpenOptions {
    /**
     * Should the file be opened with read access?
     * @defaultValue true
     */
    read?: boolean;
    /**
     * Should the file be opened with write access?
     * @defaultValue false
     */
    write?: boolean;
    /**
     * Writing: open the file in append mode.
     * Note that setting this to `true` implies setting `write` to `true`.
     * @defaultValue false
     */
    append?: boolean;
    /**
     * Writing: truncate (remove all contents of) the file.
     * Note that this only works if `write` is `true`.
     * @defaultValue false
     */
    truncate?: boolean;
    /**
     * Writing: create a new file if it doesn't exist.
     * Note that this only works if `write` or `append` are set to `true`.
     * @defaultValue false
     */
    create?: boolean;
    /**
     * Writing: always create a new file, even if one already exists.
     * Note that this only works if `write` or `append` are set to `true`.
     * Note that `create` and `truncate` are ignored if this is set to `true`.
     * @defaultValue false
     */
    createNew?: boolean;
}
/**
 * File represents a file handle.
 */
declare class File {
    /**
     * The file path
     */
    readonly path: string;
    private constructor();
    /**
     * Opens a file.
     * 
     * Example
     * ```js
     * // Open a file for reading
     * let file = await File.open("my_file.txt", {
     * read: true,
     * });
     * 
     * // Create a new file for writing.
     * let file = await File.open("my_file.txt", {
     * write: true,
     * createNew: true,
     * });
     * 
     * // Append to an existing file.
     * let file = await File.open("my_file.txt", {
     * write: true,
     * append: true,
     * });
     * ```
     */
    static open(path: string, options?: OpenOptions): Promise<File>;
    /**
     * Returns true if the file is open.
     */
    isOpen(): boolean;
    /**
     * Closes this file handle.
     * Please note that the actual file might not be closed until all other handles to it are also closed.
     * This can happen if you cloned() this File.
     */
    close(): void;
    writeBytes(bytes: Uint8Array): Promise<void>;
    static writeBytes(path: string, bytes: Uint8Array): Promise<void>;
    writeText(text: string): Promise<void>;
    static writeText(path: string, text: string): Promise<void>;
    readBytes(amount?: number): Promise<Uint8Array>;
    static readBytes(path: string, amount?: number): Promise<Uint8Array>;
    readText(): Promise<string>;
    static readText(path: string): Promise<string>;
    size(): Promise<number>;
    setSize(size: number): Promise<void>;
    readonly(): Promise<boolean>;
    setReadonly(readonly: boolean): Promise<void>;
    /**
     * @platform does not work on Windows
     */
    mode(): Promise<number>;
    /**
     * Sets the file mode.
     * You should use the octal notation to specify the mode: `await file.setMode(0o445)`.
     * @platform does not work on Windows
     */
    setMode(mode: number): Promise<void>;
    modifiedTime(): Promise<Date>;
    setModifiedTime(date: Date): Promise<void>;
    accessedTime(): Promise<Date>;
    setAccessedTime(date: Date): Promise<void>;
    creationTime(): Promise<Date>;
    /**
     * @platform does not work on Linux
     */
    setCreationTime(date: Date): Promise<void>;
    position(): Promise<number>;
    setPosition(position: number): Promise<void>;
    setRelativePosition(offset: number): Promise<void>;
    rewind(): Promise<void>;
    static exists(path: string): Promise<boolean>;
    /**
     * Removes a file from the filesystem.
     * 
     * Note that there is no guarantee that the file is immediately deleted (e.g. depending on platform, other open file descriptors may prevent immediate removal).
     */
    static remove(path: string): Promise<void>;
    static copy(source: string, destination: string): Promise<void>;
    static rename(source: string, destination: string): Promise<void>;
    static move(source: string, destination: string): Promise<void>;
    clone(): File;
    equals(other: File): boolean;
    toString(): string;
}
declare class Filesystem {
    private constructor();
    static exists(path: string): Promise<boolean>;
    static isFile(path: string): Promise<boolean>;
    static isDirectory(path: string): Promise<boolean>;
    static isSymlink(path: string): Promise<boolean>;
}
/**
 * An iterator over the variants of [JsFlipDirection]
 */
declare interface FlipDirectionIter {
}
/**
 * An iterator over the variants of [JsResizeFilter]
 */
declare interface ResizeFilterIter {
}
/**
 * An iterator over the variants of [JsInterpolation]
 */
declare interface InterpolationIter {
}
/**
 * Resize options
 */
declare interface ResizeOptions {
    /**
     * Should the aspect ratio be kept?
     * @defaultValue false
     */
    keepAspectRatio?: boolean;
    /**
     * What filter to use
     * @defaultValue ResizeFilter.CUBIC
     */
    filter?: ResizeFilter;
}
/**
 * Blur options
 */
declare interface BlurOptions {
    /**
     * Perform a fast, lower quality blur
     * @defaultValue false
     */
    fast?: boolean;
    /**
     * Standard deviation of the (approximated) Gaussian
     * @defaultValue 2
     */
    sigma?: number;
}
/**
 * Draw image options
 */
declare interface DrawImageOptions {
    /**
     * Source rectangle
     * @defaultValue Whole image
     */
    sourceRect?: Rect;
}
/**
 * Rotation options
 */
declare interface RotationOptions {
    /**
     * Interpolation algorithm (used if the rotation angle is different from 90, 180, and 270 degrees and no center position has been set)
     * @defaultValue Interpolation.Bilinear
     */
    interpolation?: Interpolation;
    /**
     * Rotation center
     * @defaultValue image center
     */
    center?: Point;
    /**
     * Default color, used if the rotation triggers more pixels to be displayed
     * @defaultValue Color.Black
     */
    defaultColor?: Color;
}
/**
 * Drawing options
 */
declare interface DrawingOptions {
    /**
     * Draw a hollow shape instead of a filled one
     * @defaultValue false
     */
    hollow?: boolean;
}
declare class AbortSignal {
    private constructor();
}
declare class AbortController {
    readonly signal: AbortSignal;
    constructor();
    abort(): void;
}
declare interface Keyboard {
}
declare const keyboard: Keyboard;
declare interface Mouse {
    /**
     * @platform does not work on Wayland
     */
    isPressed(button: Button): Promise<boolean>;
    scroll(length: number, axis?: Axis): Promise<void>;
    /**
     * @platform does not work on Wayland
     */
    position(): Promise<Point>;
    measureSpeed(duration?: number): Promise<number>;
    move(point: Point, options?: MoveOptions): Task<void>;
    move(x: number, y: number, options?: MoveOptions): Task<void>;
    move(o: {x: number, y: number}, options?: MoveOptions): Task<void>;
    setPosition(point: Point): Promise<void>;
    setPosition(x: number, y: number): Promise<void>;
    setPosition(o: {x: number, y: number}): Promise<void>;
    setRelativePosition(point: Point): Promise<void>;
    setRelativePosition(x: number, y: number): Promise<void>;
    setRelativePosition(o: {x: number, y: number}): Promise<void>;
    click(options?: ClickOptions): Promise<void>;
    doubleClick(options?: DoubleClickOptions): Promise<void>;
    press(options?: PressOptions): Promise<void>;
    release(button?: Button): Promise<void>;
}
declare const mouse: Mouse;
declare interface Random {
    /**
     * Returns a number between 0 (inclusive) and 1 (exclusive)
     */
    number(): number;
    /**
     * Returns a number between 0 (inclusive) and max (exclusive)
     */
    number(max: number): number;
    /**
     * Returns a number between min (inclusive) and max (exclusive)
     */
    number(min: number, max: number): number;
    /**
     * Returns an integer between 0 (inclusive) and max (inclusive)
     */
    integer(max: number): number;
    /**
     * Returns an integer between min (inclusive) and max (inclusive)
     */
    integer(min: number, max: number): number;
    /**
     * Sets the seed to a value.
     * This seed is used for all random number generation. Since the random number generator is
     * deterministic that means that setting it to a particular number will always generate the same
     * random numbers.
     */
    setSeed(seed: number): void;
    /**
     * Resets the seed to be a random one.
     */
    resetSeed(): void;
    /**
     * Returns a random position on any display.
     */
    position(): Point;
    /**
     * Chooses one random entry in an array.
     * A fallback can be provided, in case the array is empty.
     */
    choice<T>(array: Array<T>, fallback?: T): T;
}
declare const random: Random;
declare interface Screenshot {
}
declare const screenshot: Screenshot;
declare interface Ui {
    static messageBox(text: string, options?: MessageBoxOptions): Promise<MessageBoxResult>;
}
declare const ui: Ui;
declare interface Web {
    /**
     * Downloads a binary file.
     */
    download(url: string, options?: WebOptions): ProgressTask<Uint8Array, WebProgress>;
    /**
     * Downloads a text file.
     */
    downloadText(url: string, options?: WebOptions): ProgressTask<string, WebProgress>;
    /**
     * Downloads an image.
     */
    downloadImage(url: string, options?: WebOptions): ProgressTask<Image, WebProgress>;
    /**
     * Downloads a file to a directory.
     */
    downloadFile(url: string, directory?: string, options?: WebOptions): ProgressTask<string, WebProgress>;
}
declare const web: Web;
declare class Wildcard {
    /**
     * Constructor.
     */
    constructor(pattern: string);
}
declare class Name {
    /**
     * Constructor with a fixed name.
     */
    constructor(name: string);
    /**
     * Constructor with a wildcard.
     */
    constructor(wildcard: Wildcard);
    /**
     * Constructor with a regular expression.
     */
    constructor(regexp: RegExp);
}
declare class Path {
    private constructor();
    static join(...args: string[]): string;
    static filename(path: string): string;
    static basename(path: string): string;
    static parent(path: string): string;
    static dirname(path: string): string;
    static isAbsolute(path: string): boolean;
    static isRelative(path: string): boolean;
    static extension(path: string): string;
    static extname(path: string): string;
    static setExtension(path: string, extension: string): string;
}
/**
 * A size.
 * 
 * 
 * ```js
 * let p = new Size(1, 2);
 * ```
 */
declare class Size {
    /**
     * width
     */
    width: number;
    /**
     * height
     */
    height: number;
    /**
     * Constructor with two numbers.
     */
    constructor(width: number, height: number);
    /**
     * Constructor with an object.
     */
    constructor(o: {width: number, height: number});
    /**
     * Constructor with another Size.
     */
    constructor(p: Size);
    /**
     * Returns a JSON representation of this Size.
     */
    toJson(): string;
    /**
     * Returns true if a Size equals another.
     */
    equals(other: Size): boolean;
    /**
     * Returns true if a Size equals another.
     */
    equals(width: number, height: number): boolean;
    /**
     * Returns true if a Size equals another.
     */
    equals(o: {width: number, height: number}): boolean;
    /**
     * Adds two sizes and returns a new Size.
     */
    add(other: Size): Size;
    /**
     * Adds two sizes and returns a new Size.
     */
    add(width: number, height: number): Size;
    /**
     * Adds two sizes and returns a new Size.
     */
    add(o: {width: number, height: number}): Size;
    /**
     * Subtracts two sizes and returns a new Size.
     */
    subtract(other: Size): Size;
    /**
     * Subtracts two sizes and returns a new Size.
     */
    subtract(width: number, height: number): Size;
    /**
     * Subtracts two sizes and returns a new Size.
     */
    subtract(o: {width: number, height: number}): Size;
    /**
     * Scales this size by a factor and returns a new Size.
     */
    scale(factor: number): Size;
    /**
     * Returns a string representation of this Size.
     */
    toString(): string;
    /**
     * Clones this Size.
     */
    clone(): Size;
}
declare class MessageBoxButtons {
    private constructor();
    static intoInner(self: MessageBoxButtons): MessageBoxButtons;
    static ok(): MessageBoxButtons;
    static okCustom(ok_label: string): MessageBoxButtons;
    static okCancel(): MessageBoxButtons;
    static okCancelCustom(ok_label: string, cancel_label: string): MessageBoxButtons;
    static yesNo(): MessageBoxButtons;
    static yesNoCancel(): MessageBoxButtons;
    static yesNoCancelCustom(yes_label: string, no_label: string, cancel_label: string): MessageBoxButtons;
}
/**
 * Multipart form
 */
declare interface MultipartForm {
}
declare class WebProgress {
    private constructor();
    current(): number;
    finished(): boolean;
    total(): number;
}
declare interface Concurrency {
    race<T>(promises: Iterable<T|PromiseLike<T>>): Task<Awaited<T>>;
}
/**
 * Web options
 */
declare interface WebOptions {
    /**
     * @defaultValue undefined
     */
    signal?: AbortSignal;
    /**
     * @defaultValue undefined
     */
    userName?: string;
    /**
     * @defaultValue undefined
     */
    password?: string;
    /**
     * @defaultValue undefined
     */
    headers?: Record<string, string>;
    /**
     * @defaultValue Method.GET
     */
    method?: Method;
    /**
     * @defaultValue undefined
     */
    timeout?: number;
    /**
     * Sets the content-type header.
     * Overrides any content-type set by other fields.
     * @defaultValue undefined
     */
    contentType?: string;
    /**
     * Form data as strings.
     * Sets content-type to "application/x-www-form-urlencoded".
     * @defaultValue undefined
     */
    form?: Record<string, string>;
    /**
     * Additional query parameters.
     * @defaultValue undefined
     */
    query?: Record<string, string>;
    /**
     * Form multipart data.
     * Sets content-type and content-length appropriately.
     * @defaultValue undefined
     */
    multipart?: MultipartForm;
}
/**
 * Find image options
 */
declare interface FindImageOptions {
}
/**
 * Move options
 */
declare interface MoveOptions {
    /**
     * @defaultValue 2000
     */
    speed?: number;
    /**
     * @defaultValue Tween.SINE_OUT
     */
    tween?: Tween;
    /**
     * @defaultValue 50
     */
    perlinScale?: number;
    /**
     * @defaultValue 5
     */
    perlinAmplitude?: number;
    /**
     * @defaultValue 0
     */
    targetRandomness?: number;
    /**
     * Interval in milliseconds
     * @defaultValue 10
     */
    interval?: number;
}
/**
 * Button click options
 */
declare interface ClickOptions extends PressOptions {
    /**
     * @defaultValue 1
     */
    amount?: number;
    /**
     * @defaultValue 0
     */
    interval?: number;
    /**
     * @defaultValue 0
     */
    duration?: number;
}
/**
 * Button double click options
 */
declare interface DoubleClickOptions extends ClickOptions {
    /**
     * @defaultValue 250
     */
    delay?: number;
}
/**
 * Button press options
 */
declare interface PressOptions {
    /**
     * @defaultValue Button.LEFT
     */
    button?: Button;
    /**
     * @defaultValue undefined
     */
    position?: Point;
    /**
     * @defaultValue false
     */
    relativePosition?: boolean;
}
