pub mod button_condition;
pub mod click;
pub mod double_click;
pub mod get_cursor_position;
pub mod move_cursor;
pub mod press;
pub mod release;
pub mod scroll;
pub mod set_cursor_position;
pub mod wait_for_button;
pub mod wait_for_movement;
pub mod wait_for_scroll;

pub use button_condition::ButtonCondition;
pub use click::{Click, MouseButton};
pub use double_click::DoubleClick;
pub use get_cursor_position::GetCursorPosition;
pub use move_cursor::{MoveCursor, Tween};
pub use press::Press;
pub use release::Release;
pub use scroll::Scroll;
pub use set_cursor_position::SetCursorPosition;
pub use wait_for_button::WaitForButton;
pub use wait_for_movement::WaitForMovement;
pub use wait_for_scroll::WaitForScroll;
