[package]
name = "extension"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = [
    "Win32_Security",
    "Win32_System_JobObjects",
    "Win32_System_Threading",
] }

[dependencies]
color-eyre.workspace = true
derive-where.workspace = true
futures-util.workspace = true
image.workspace = true
ipc-rpc.workspace = true
macros = { path = "../macros" }
parking_lot.workspace = true
serde.workspace = true
strum = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["signal"] }
tokio-util = { workspace = true, features = ["rt", "codec"] }
tracing.workspace = true
types = { path = "../types" }
uuid = { workspace = true, features = ["serde", "v4"] }

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
